//! Tests for maskgit.zig against golden values from the C++ reference
//! (refs/omnivoice.cpp/src/maskgit-tts.h), generated by a standalone harness
//! that #includes the verbatim reference header (LLM plumbing stubbed, math
//! untouched), compiled clang++ -std=c++17 -O2 -ffp-contract=off. Goldens are
//! f32 bit patterns.
//!
//! -ffp-contract=off because the parity target is unfused IEEE mul+add (what
//! PyTorch's elementwise kernels do and what Zig always emits); a default
//! clang -O2 build (contract on) fuses `1+(t_shift-1)*t`, `x*inv_t + g` and
//! `c + g*(c-u)` into fma and wiggles 1-2 ulp on some values — the schedule
//! integers are identical either way (verified), so greedy decode parity is
//! unaffected.
//!
//! Everything without libm calls asserts bit-exact. @exp/@log under
//! standalone `zig test` (no libc) come from Zig's own f32 math, which can
//! differ from the Apple libm the harness linked by ~1 ulp per call; outputs
//! downstream of exp/log use a small ulp tolerance with the observed maximum
//! noted inline.

const std = @import("std");
const maskgit = @import("maskgit.zig");

const neg_inf_bits: u32 = 0xff800000;

/// Pseudo-logits in [-10, 10): the harness's LCG (exact u32 ops + one f32
/// rounding per element), replicated bit-for-bit.
fn lcgFill(state: *u32, out: []f32) void {
    for (out) |*x| {
        state.* = state.* *% 1664525 +% 1013904223;
        x.* = @as(f32, @floatFromInt(state.* >> 8)) * (20.0 / 16777216.0) - 10.0;
    }
}

fn expectBits(expected: []const u32, actual: []const f32) !void {
    try std.testing.expectEqual(expected.len, actual.len);
    for (expected, actual) |e, a| {
        try std.testing.expectEqual(e, @as(u32, @bitCast(a)));
    }
}

/// Same-sign adjacent f32 values have adjacent bit patterns, so a u32 bit
/// distance is a ulp distance for the magnitudes involved here.
fn expectBitsUlp(expected: []const u32, actual: []const f32, max_ulp: u32) !void {
    try std.testing.expectEqual(expected.len, actual.len);
    for (expected, actual) |e, a| {
        const bits: u32 = @bitCast(a);
        const diff = if (bits > e) bits - e else e - bits;
        if (diff > max_ulp) {
            std.debug.print("expected 0x{x:0>8} got 0x{x:0>8} ({} ulp)\n", .{ e, bits, diff });
            return error.TestExpectedEqual;
        }
    }
}

/// Like expectBitsUlp, but also passes when the absolute error is <= max_abs:
/// in x*inv_t + g the addends (magnitude up to ~5 here) can cancel, so a
/// 1-ulp @log-vs-Apple-libm wiggle in g yields a large bit distance on a
/// near-zero result while the absolute error stays ~1e-7 (observed max:
/// 6e-8 at one element, 32 "ulp" of a 0.04-magnitude output).
fn expectBitsUlpOrAbs(expected: []const u32, actual: []const f32, max_ulp: u32, max_abs: f32) !void {
    try std.testing.expectEqual(expected.len, actual.len);
    for (expected, actual) |e, a| {
        const bits: u32 = @bitCast(a);
        const diff = if (bits > e) bits - e else e - bits;
        if (diff > max_ulp and !(@abs(a - @as(f32, @bitCast(e))) <= max_abs)) {
            std.debug.print("expected 0x{x:0>8} got 0x{x:0>8} ({} ulp)\n", .{ e, bits, diff });
            return error.TestExpectedEqual;
        }
    }
}

test "lcg pseudo-logits match the harness bit-exactly" {
    var s: u32 = 12345;
    var x: [4]f32 = undefined;
    lcgFill(&s, &x);
    try expectBits(&.{ 0xc119789d, 0xc11ab468, 0x3f5cf520, 0x402cad58 }, &x);
}

test "timesteps bit-exact (num_step 32 and 8, t_shift 0.1)" {
    var ts32: [33]f32 = undefined;
    maskgit.timesteps(0.1, 32, &ts32);
    try expectBits(&.{
        0x00000000, 0x3b52ba08, 0x3bd901b2, 0x3c27c118, 0x3c66c2b5, 0x3c94f209, 0x3cb8c82f, 0x3cdf20de,
        0x3d042109, 0x3d1a3e20, 0x3d321643, 0x3d4bdf91, 0x3d67d95c, 0x3d832719, 0x3d93cb36, 0x3da60dd6,
        0x3dba2e8c, 0x3dd07aa2, 0x3de95103, 0x3e0293c2, 0x3e124925, 0x3e242716, 0x3e38a7de, 0x3e506cbd,
        0x3e6c4ec3, 0x3e86bca2, 0x3e9aca6b, 0x3eb3884f, 0x3ed2d2d0, 0x3efba935, 0x3f19999a, 0x3f418f9c,
        0x3f7ffffc,
    }, &ts32);

    var ts8: [9]f32 = undefined;
    maskgit.timesteps(0.1, 8, &ts8);
    try expectBits(&.{
        0x00000000, 0x3c66c2b5, 0x3d042109, 0x3d67d95c, 0x3dba2e8c, 0x3e124925, 0x3e6c4ec3, 0x3ed2d2d0,
        0x3f7ffffc,
    }, &ts8);
}

test "schedule matches the reference for (num_step, total) grid" {
    const Case = struct { num_step: usize, total: usize, want: []const i32 };
    const cases = [_]Case{
        .{ .num_step = 32, .total = 8 * 27, .want = &.{
            1, 1, 1,  1,  1,  1,  2,  2,
            2, 2, 2,  2,  2,  2,  2,  3,
            3, 3, 3,  4,  4,  5,  6,  6,
            7, 9, 11, 14, 18, 24, 34, 38,
        } },
        .{ .num_step = 32, .total = 8 * 350, .want = &.{
            10, 10,  11,  11,  12,  13,  14,  15,
            16, 17,  18,  20,  21,  23,  25,  28,
            31, 34,  39,  43,  49,  57,  65,  77,
            91, 110, 136, 172, 224, 304, 438, 666,
        } },
        .{ .num_step = 32, .total = 8 * 1, .want = &.{
            1, 1, 1, 1, 1, 1, 1, 1,
            0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0,
        } },
        .{ .num_step = 8, .total = 8 * 27, .want = &.{ 4, 4, 6, 8, 12, 19, 40, 123 } },
        .{ .num_step = 8, .total = 8 * 350, .want = &.{ 40, 51, 69, 97, 146, 247, 507, 1643 } },
        .{ .num_step = 8, .total = 8 * 1, .want = &.{ 1, 1, 1, 1, 1, 1, 2, 0 } },
    };
    for (cases) |case| {
        var ts_buf: [33]f32 = undefined;
        const ts = ts_buf[0 .. case.num_step + 1];
        maskgit.timesteps(0.1, case.num_step, ts);

        var out_buf: [32]i32 = undefined;
        const out = out_buf[0..case.num_step];
        maskgit.schedule(case.total, ts, out);
        try std.testing.expectEqualSlices(i32, case.want, out);

        var sum: i64 = 0;
        for (out) |v| sum += v;
        try std.testing.expectEqual(@as(i64, @intCast(case.total)), sum);
    }
}

test "logSoftmaxInplace on the 1025-float LCG vector" {
    var s: u32 = 12345;
    var x: [1025]f32 = undefined;
    lcgFill(&s, &x);

    // The reference max scan is comparison-only: bit-exact.
    try std.testing.expectEqual(@as(u32, 0x411ff9ee), @as(u32, @bitCast(maskgit.maxValue(&x))));

    maskgit.logSoftmaxInplace(&x);
    // Outputs = x - lse where lse crossed 1025 @exp calls + one @log; Zig math
    // vs Apple libm drift observed: 0 ulp on this data, tolerance 2 for slack.
    try expectBitsUlp(&.{
        0xc1bc504a, 0xc1bcee30, 0xc15158a6, 0xc133fca2, 0xc0b7e4b4, 0xc1ad958e, 0xc16078b6, 0xc14faf3b,
        0xc1406773, 0xc10473b7, 0xc1b9338e, 0xc11123c7, 0xc09431bc, 0xc1b3ca90, 0xc11f482c, 0xc16bdcac,
    }, x[0..16], 2);
    try expectBitsUlp(&.{ 0xc199a38b, 0xc12751a3, 0xc1bc93a8, 0xc15a2d0c }, x[1021..], 2);
}

test "topKFilterInplace ratio=0.1 on the 1025-float LCG vector" {
    var s: u32 = 777;
    var x: [1025]f32 = undefined;
    lcgFill(&s, &x);
    try expectBits(&.{ 0x3f3e71c0, 0x40a37380, 0x40d83b34, 0xbfb44460 }, x[0..4]);

    maskgit.topKFilterInplace(&x, 0.1);

    // kk = ceil(0.1 * 1025) = 103; comparison-only math: all bit-exact.
    const neg_inf = -std.math.inf(f32);
    var survivors: usize = 0;
    var threshold = std.math.inf(f32);
    for (x) |v| {
        if (v != neg_inf) {
            survivors += 1;
            if (v < threshold) threshold = v;
        }
    }
    try std.testing.expectEqual(@as(usize, 103), survivors);
    try std.testing.expectEqual(@as(u32, 0x40fb5b64), @as(u32, @bitCast(threshold)));
    for (x[0..16]) |v| {
        try std.testing.expectEqual(neg_inf_bits, @as(u32, @bitCast(v)));
    }
}

test "topKFilterInplace keeps threshold ties and handles kk out of range" {
    // kk = ceil(0.5 * 4) = 2, threshold = 2nd largest = 5.0: all ties survive.
    var ties = [_]f32{ 5.0, 5.0, 5.0, 1.0 };
    maskgit.topKFilterInplace(&ties, 0.5);
    try expectBits(&.{ 0x40a00000, 0x40a00000, 0x40a00000, neg_inf_bits }, &ties);

    // kk >= n and kk <= 0 are no-ops (reference early return).
    var untouched = [_]f32{ 3.0, 1.0, 2.0, 0.0 };
    maskgit.topKFilterInplace(&untouched, 1.0);
    try expectBits(&.{ 0x40400000, 0x3f800000, 0x40000000, 0x00000000 }, &untouched);
    maskgit.topKFilterInplace(&untouched, 0.0);
    try expectBits(&.{ 0x40400000, 0x3f800000, 0x40000000, 0x00000000 }, &untouched);
}

test "gumbelInplace chained kernels: temperature=5 seed=42, ctr_lo threads" {
    var s: u32 = 999;
    var ctr_lo: u32 = 0;
    var a: [16]f32 = undefined;
    var b: [16]f32 = undefined;
    var c: [16]f32 = undefined;
    lcgFill(&s, &a);
    lcgFill(&s, &b);
    lcgFill(&s, &c);
    c[0] = -std.math.inf(f32);

    try expectBits(&.{
        0x401dbcf0, 0x40faa460, 0x40db9524, 0x403c6fe0, 0xc0ca52ee, 0x3fd981d0, 0x410fe928, 0x40f12e30,
        0x408915f0, 0x41174f44, 0xc10a0858, 0x40e98d04, 0xbd130200, 0x40a096e6, 0xc0fcbc19, 0xc0e3eac0,
    }, &a);

    // The Philox uniforms are bit-identical to the reference (philox_tests);
    // only the two nested @log calls can wiggle vs Apple libm. Observed drift:
    // 0 ulp on all 48 outputs, tolerance 2 for slack.
    maskgit.gumbelInplace(&a, 5.0, 42, &ctr_lo);
    try std.testing.expectEqual(@as(u32, 1), ctr_lo);
    try expectBitsUlpOrAbs(&.{
        0x3f9a8bd6, 0x3d2654e0, 0x3fba4d58, 0xbf13e93b, 0xbff107d2, 0x3f27fab7, 0x403ee03e, 0x3fce3994,
        0x3fa39fb8, 0x3fd59b55, 0xc004e49e, 0x407ed3c6, 0x3fd614aa, 0xbe5a1598, 0xbfc33875, 0xc015b6e3,
    }, &a, 2, 1e-6);

    maskgit.gumbelInplace(&b, 5.0, 42, &ctr_lo);
    try std.testing.expectEqual(@as(u32, 2), ctr_lo);
    try expectBitsUlpOrAbs(&.{
        0x40a75137, 0xbf3ae5e0, 0x3f9d747e, 0x3f15e143, 0x4039d3aa, 0x3ff1a5f4, 0x40a5abfd, 0x40712915,
        0x3f071261, 0x3fb9348a, 0x3fac86f6, 0x40046191, 0x3f1e65d8, 0x3f8068c2, 0x3fd30dfe, 0x3fb8368a,
    }, &b, 2, 1e-6);

    maskgit.gumbelInplace(&c, 5.0, 42, &ctr_lo);
    try std.testing.expectEqual(@as(u32, 3), ctr_lo);
    // -inf stays exactly -inf through x*inv_t + g.
    try std.testing.expectEqual(neg_inf_bits, @as(u32, @bitCast(c[0])));
    try expectBitsUlpOrAbs(&.{
        neg_inf_bits, 0xbfe47a29, 0x4041875d, 0xbea4a1a3, 0x3f13b86b, 0xbf839f2e, 0x402c3462, 0x3f8a7e99,
        0x3ff5c9b4,   0x40e8913c, 0x3f80b4fc, 0x3f7b81f6, 0x401116b0, 0xbf92dd2c, 0x40210513, 0x3f79f8c6,
    }, &c, 2, 1e-6);
}

test "gumbelInplace draws span multiple chunks bit-identically" {
    // 300 elements exceed the 256-float internal chunk; each element only
    // depends on its own Philox subsequence, so chunking must be invisible.
    var x = [_]f32{0.0} ** 300;
    var ctr_lo: u32 = 5;
    maskgit.gumbelInplace(&x, 5.0, 42, &ctr_lo);
    try std.testing.expectEqual(@as(u32, 6), ctr_lo);

    // Element 299 recomputed standalone: uniform for subsequence 299 at
    // ctr_lo=5, pushed through the same formula.
    const philox = @import("philox.zig");
    var u_one: [1]f32 = undefined;
    philox.uniformFill(42, 299, 5, &u_one);
    const g = -@log(-@log(u_one[0] + 1e-10) + 1e-10);
    try std.testing.expectEqual(@as(u32, @bitCast(g)), @as(u32, @bitCast(x[299])));
}

test "cfgCombine g=2 matches the reference CFG pipeline" {
    var s: u32 = 4242;
    var c: [32]f32 = undefined;
    var u: [32]f32 = undefined;
    var lp: [32]f32 = undefined;
    lcgFill(&s, &c);
    lcgFill(&s, &u);
    try expectBits(&.{ 0x40f33de8, 0xc111f08b, 0xc03d6874, 0x4074da40 }, c[0..4]);
    try expectBits(&.{ 0x409af5d6, 0x4077d9d8, 0x40421660, 0x41088fa0 }, u[0..4]);

    maskgit.cfgCombine(&c, &u, 2.0, &lp);
    // Three log_softmax passes (3 @log + 96 @exp); observed drift 0 ulp,
    // tolerance 2 for slack.
    try expectBitsUlp(&.{
        0xc1f70e08, 0xc29e3834, 0xc26bc727, 0xc2465fa9, 0xc1ee9138, 0xc205a94a, 0xc1558f0c, 0xb99e0000,
        0xc234d198, 0xc291b248, 0xc2184ce5, 0xc22a454c, 0xc281db7c, 0xc21e73a2, 0xc1c6d772, 0xc22d9a69,
        0xc280fe23, 0xc1e61a22, 0xc206f3da, 0xc2563ae4, 0xc2a34b2c, 0xc261f042, 0xc261b40b, 0xc25dcb3d,
        0xc2a05d08, 0xc217e53a, 0xc294897f, 0xc1ef5dda, 0xc202b721, 0xc2235859, 0xc101e034, 0xc286ed16,
    }, &lp, 2);
}

test "cfgCombine mutates c/u in place when g != 0, copies when g == 0" {
    var s: u32 = 4242;
    var c: [32]f32 = undefined;
    var u: [32]f32 = undefined;
    var lp: [32]f32 = undefined;
    lcgFill(&s, &c);
    lcgFill(&s, &u);

    var c_ref = c;
    var u_ref = u;
    maskgit.logSoftmaxInplace(&c_ref);
    maskgit.logSoftmaxInplace(&u_ref);

    maskgit.cfgCombine(&c, &u, 2.0, &lp);
    try std.testing.expectEqualSlices(f32, &c_ref, &c);
    try std.testing.expectEqualSlices(f32, &u_ref, &u);

    // g == 0: lp = log_softmax(c), c and u untouched.
    var cg0: [32]f32 = undefined;
    var ug0: [32]f32 = undefined;
    lcgFill(&s, &cg0);
    lcgFill(&s, &ug0);
    const cg0_pristine = cg0;
    const ug0_pristine = ug0;
    var want = cg0;
    maskgit.logSoftmaxInplace(&want);
    maskgit.cfgCombine(&cg0, &ug0, 0.0, &lp);
    try std.testing.expectEqualSlices(f32, &want, &lp);
    try std.testing.expectEqualSlices(f32, &cg0_pristine, &cg0);
    try std.testing.expectEqualSlices(f32, &ug0_pristine, &ug0);
}

test "argmaxStrict and maxValue: first index wins ties" {
    const ties = [_]f32{ 1.0, 3.0, 3.0, 2.0 };
    try std.testing.expectEqual(@as(usize, 1), maskgit.argmaxStrict(&ties));
    try std.testing.expectEqual(@as(f32, 3.0), maskgit.maxValue(&ties));

    const single = [_]f32{-4.5};
    try std.testing.expectEqual(@as(usize, 0), maskgit.argmaxStrict(&single));
    try std.testing.expectEqual(@as(f32, -4.5), maskgit.maxValue(&single));

    const neg_inf = -std.math.inf(f32);
    const infs = [_]f32{ neg_inf, neg_inf, neg_inf };
    try std.testing.expectEqual(@as(usize, 0), maskgit.argmaxStrict(&infs));
    try std.testing.expectEqual(neg_inf, maskgit.maxValue(&infs));
}

test "topKSelect matches std::partial_sort golden on distinct values" {
    var s: u32 = 31337;
    var conf: [24]f32 = undefined;
    lcgFill(&s, &conf);
    try expectBits(&.{ 0xc0189400, 0x404ff184, 0x3ee81480, 0x403fa604 }, conf[0..4]);

    var idx: [5]usize = undefined;
    maskgit.topKSelect(&conf, 5, &idx);
    try std.testing.expectEqualSlices(usize, &.{ 13, 21, 9, 6, 11 }, &idx);
}

test "topKSelect deterministic tie order: descending value, ascending index" {
    // Tie order in the reference partial_sort is unspecified; greedy parity
    // never depends on it (post-penalty scores are distinct in practice).
    const conf = [_]f32{ 1.0, 2.0, 2.0, 2.0 };
    var idx2: [2]usize = undefined;
    maskgit.topKSelect(&conf, 2, &idx2);
    try std.testing.expectEqualSlices(usize, &.{ 1, 2 }, &idx2);

    var idx4: [4]usize = undefined;
    maskgit.topKSelect(&conf, 4, &idx4);
    try std.testing.expectEqualSlices(usize, &.{ 1, 2, 3, 0 }, &idx4);

    // k = 0 writes nothing.
    var untouched = [_]usize{ 99, 99 };
    maskgit.topKSelect(&conf, 0, &untouched);
    try std.testing.expectEqualSlices(usize, &.{ 99, 99 }, &untouched);

    // -inf entries (already-decoded slots) sort last.
    const neg_inf = -std.math.inf(f32);
    const masked = [_]f32{ neg_inf, 4.0, neg_inf, 3.0 };
    var idxm: [3]usize = undefined;
    maskgit.topKSelect(&masked, 3, &idxm);
    try std.testing.expectEqualSlices(usize, &.{ 1, 3, 0 }, &idxm);
}
