//! Tests for philox.zig against golden values from the C++ reference
//! (refs/omnivoice.cpp/src/philox.h), generated by a standalone harness
//! compiled with clang++ -O2 (identical output with -ffp-contract=off).
//! All goldens are f32/u32 bit patterns.

const std = @import("std");
const philox = @import("philox.zig");

fn expectBits(expected: []const u32, actual: []const f32) !void {
    try std.testing.expectEqual(expected.len, actual.len);
    for (expected, actual) |e, a| {
        try std.testing.expectEqual(e, @as(u32, @bitCast(a)));
    }
}

/// Box-Muller outputs go through logf/sinf/cosf; Zig's own f32 math (used when
/// libc is not linked, as under standalone `zig test`) differs from the Apple
/// libm the golden harness linked by at most 1 ulp on these inputs (observed:
/// exactly one of 12 values, randn(42, 2), off by 1 ulp). Everything without
/// libm calls is asserted bit-exact.
fn expectBitsUlp1(expected: []const u32, actual: []const f32) !void {
    try std.testing.expectEqual(expected.len, actual.len);
    for (expected, actual) |e, a| {
        const bits: u32 = @bitCast(a);
        const diff = if (bits > e) bits - e else e - bits;
        if (diff > 1) return error.TestExpectedEqual;
    }
}

fn expectF32Ulp1(expected: f32, actual: f32) !void {
    const e: u32 = @bitCast(expected);
    const a: u32 = @bitCast(actual);
    const diff = if (a > e) a - e else e - a;
    if (diff > 1) return error.TestExpectedEqual;
}

test "philox4x32_10 zero block matches the Random123 known-answer vector" {
    const r = philox.philox4x32_10(.{ 0, 0, 0, 0 }, 0, 0);
    try std.testing.expectEqual([4]u32{ 0x6627e8d5, 0xe169c58d, 0xbc57ac4c, 0x9b00dbd8 }, r);
}

test "philox4x32_10 arbitrary counter/key block" {
    const r = philox.philox4x32_10(
        .{ 0x01234567, 0x89abcdef, 0xdeadbeef, 0xcafebabe },
        0xa5a5a5a5,
        0x5a5a5a5a,
    );
    try std.testing.expectEqual([4]u32{ 0x80ae47c1, 0xed59e7a6, 0x6cc6c5f6, 0xe783dc5f }, r);
}

test "uniformFill bit-exact over seeds x ctr_lo" {
    const Case = struct { seed: u64, ctr_lo: u32, want: [8]u32 };
    const cases = [_]Case{
        .{ .seed = 42, .ctr_lo = 0, .want = .{ 0x3f1ceaf0, 0x3c24cdda, 0x3ecbfce1, 0x3d251a6b, 0x3e200464, 0x3ef706b6, 0x3f3c7ab4, 0x3ecfdcde } },
        .{ .seed = 42, .ctr_lo = 1, .want = .{ 0x3f7cdb21, 0x3e03fe45, 0x3f0fe60f, 0x3f05a8df, 0x3f3e9616, 0x3f18712c, 0x3f76f709, 0x3f65dde9 } },
        .{ .seed = 42, .ctr_lo = 7, .want = .{ 0x3eb77b07, 0x3e98f189, 0x3ea89a0d, 0x3ecb3de6, 0x3f229386, 0x3ed47069, 0x3e81c2dc, 0x3f4d241e } },
        .{ .seed = 0, .ctr_lo = 0, .want = .{ 0x3ecc4fd2, 0x3f044516, 0x3ccc3acf, 0x3f70a90b, 0x3f72237f, 0x3f4bf694, 0x3ed47cbb, 0x3f51fc5c } },
        .{ .seed = 0, .ctr_lo = 1, .want = .{ 0x3f78e4cd, 0x3f4a7cf7, 0x3ef0261e, 0x3ea8f5bd, 0x3eab40e5, 0x3ec1ad2e, 0x3f439476, 0x3f23f6e1 } },
        .{ .seed = 0, .ctr_lo = 7, .want = .{ 0x3f28b31d, 0x3dab2295, 0x3eb5ed5f, 0x3c5da6f2, 0x3ecd5ff8, 0x3e9c6f4f, 0x3e4456fc, 0x3e3b657f } },
        .{ .seed = 0xDEADBEEFCAFEBABE, .ctr_lo = 0, .want = .{ 0x3f4386ac, 0x3f2b4683, 0x3d3b2383, 0x3d558e6c, 0x3cb253b4, 0x3eef3ae3, 0x3f2c5ebd, 0x3ed9fb35 } },
        .{ .seed = 0xDEADBEEFCAFEBABE, .ctr_lo = 1, .want = .{ 0x3eaad291, 0x3f22582e, 0x3f5ce099, 0x3f3b395e, 0x3e2ca5ee, 0x3ec937e0, 0x3f2edee5, 0x3f366e1a } },
        .{ .seed = 0xDEADBEEFCAFEBABE, .ctr_lo = 7, .want = .{ 0x3f533ffc, 0x3e0b2d01, 0x3c92ddb7, 0x3f6bb975, 0x3eb5bfd6, 0x3e9d26a5, 0x3e822fa6, 0x3f2a9675 } },
    };
    for (cases) |case| {
        var out: [8]f32 = undefined;
        philox.uniformFill(case.seed, 0, case.ctr_lo, &out);
        try expectBits(&case.want, &out);
    }
}

test "uniformFill subseq_start straddling the 32-bit boundary" {
    var out: [8]f32 = undefined;
    philox.uniformFill(42, 0xFFFFFFFE, 0, &out);
    try expectBits(&.{ 0x3c776f12, 0x3eb5cbf2, 0x3e010e6c, 0x3e9a8a25, 0x3f425bba, 0x3f1065c9, 0x3e960499, 0x3f55eff3 }, &out);
}

test "uniformFill outputs stay in (0, 1)" {
    var out: [64]f32 = undefined;
    philox.uniformFill(0xDEADBEEFCAFEBABE, 12345, 3, &out);
    for (out) |v| {
        try std.testing.expect(v > 0.0 and v < 1.0);
    }
}

test "normal4 within 1 ulp of the reference" {
    const v = philox.normal4(42, 0, 0);
    try expectBitsUlp1(&.{ 0x3e46ace2, 0xbf785e5c, 0x3ff6433a, 0xbf9e28d6 }, &v);
}

test "randnFill f32 within 1 ulp of the reference" {
    var out: [8]f32 = undefined;
    philox.randnFill(42, &out, false);
    try expectBitsUlp1(&.{ 0x3e46ace2, 0x400a53f3, 0xbe302e09, 0x3f595c00, 0xbff652b6, 0x3f272a0e, 0xbf2641c5, 0xbf51494d }, &out);
}

test "randnFill bf16 bit-exact" {
    var out: [8]f32 = undefined;
    philox.randnFill(42, &out, true);
    try expectBits(&.{ 0x3e470000, 0x400a0000, 0xbe300000, 0x3f590000, 0xbff60000, 0x3f270000, 0xbf260000, 0xbf510000 }, &out);

    var out4: [4]f32 = undefined;
    philox.randnFill(0xDEADBEEFCAFEBABE, &out4, true);
    try expectBits(&.{ 0xbf350000, 0x3e9a0000, 0xc01b0000, 0x40050000 }, &out4);
}

test "randn / randnBf16 agree with randnFill per element" {
    var f32_out: [8]f32 = undefined;
    var bf16_out: [8]f32 = undefined;
    philox.randnFill(42, &f32_out, false);
    philox.randnFill(42, &bf16_out, true);
    for (0..8) |k| {
        // `randn` and `randnFill` both flow through Box-Muller libm builtins;
        // optimized x86 builds may differ by the same 1 ulp allowed above
        // against the external reference.
        try expectF32Ulp1(f32_out[k], philox.randn(42, k));
        try std.testing.expectEqual(@as(u32, @bitCast(bf16_out[k])), @as(u32, @bitCast(philox.randnBf16(42, k))));
    }
}

test "f32ToBf16ToF32 round-to-nearest-even edge cases" {
    const cases = [_][2]u32{
        .{ 0x3f808000, 0x3f800000 }, // tie, even mantissa -> stays
        .{ 0x3f818000, 0x3f820000 }, // tie, odd mantissa -> rounds up
        .{ 0x3f807fff, 0x3f800000 }, // just below tie -> rounds down
        .{ 0x3f808001, 0x3f810000 }, // just above tie -> rounds up
        .{ 0x7f7fffff, 0x7f800000 }, // FLT_MAX -> +inf
        .{ 0xc2ed4034, 0xc2ed0000 }, // arbitrary negative
        .{ 0x00000001, 0x00000000 }, // smallest denormal -> zero
    };
    for (cases) |case| {
        const got = philox.f32ToBf16ToF32(@bitCast(case[0]));
        try std.testing.expectEqual(case[1], @as(u32, @bitCast(got)));
    }
}
