//! Evolution Strategies at scale (ES) — gradient-free training over named
//! parameter buffers, after "Evolution Strategies at Scale: LLM Fine-Tuning
//! Beyond Reinforcement Learning" (arXiv:2509.24372; reference implementation
//! github.com/VsonicV/es-at-scale — algorithm reimplemented here from the
//! paper, not ported: the reference code is under a noncommercial Academic
//! Public License).
//!
//! The algorithm is deliberately vanilla OpenAI-ES (Salimans et al. 2017)
//! with the reference's simplifications kept faithfully:
//!
//!     eps_n ~ N(0, I)                                n = 1..population
//!     R_n   = reward(theta + sigma * eps_n)          (forward passes only)
//!     C_n   = (R_n - mean(R)) / (std(R) + 1e-8)      (z-score, ddof = 0)
//!     theta += (alpha / population) * sum_n C_n * eps_n
//!
//! By default: no antithetic pairs, no rank shaping, no optimizer state,
//! and — the reference's documented deviation from the textbook update — NO
//! division by sigma in the update: the 1/sigma factor is folded into alpha
//! (their default alpha = sigma/2). Three extensions are available OPT-IN,
//! clearly beyond the reference: `reward_norm = .centered_ranks`
//! (outlier-immune fitness shaping) and `antithetic = true` (mirrored
//! +/-eps pairs; variance reduction + half the update-side noise
//! regeneration), both from Salimans et al. 2017, and `anchor_decay`
//! (anchored weight decay toward the pretrained parameters, from the same
//! group's arXiv:2605.30148 — see `AnchorDecay`). Rewards are anything the
//! caller can score from a forward pass; this module never sees data,
//! models, or losses.
//!
//! Scale comes from never materializing the population:
//!
//! - **Seed-regenerated noise.** A member's perturbation is a pure function
//!   of (seed, iteration, member, slot, element) through the counter-based
//!   splitmix64 gaussian — the vectorized `rng.gaussianFillAtFast` mapping
//!   (noise regeneration dominates full-parameter ES on CPU) — so perturb,
//!   restore, and update all REGENERATE noise on the fly: nothing of size
//!   O(params) is ever stored beyond the parameters themselves.
//! - **In-place evaluation.** `perturb`/`restore` mutate the registered
//!   buffers directly (the reference's `p.data.add_(sigma*eps)` /
//!   `add_(-sigma*eps)` scheme); one model instance serves the whole
//!   population, evaluated member by member.
//! - **Chunk-parallel kernels.** Because element j's noise is O(1)-random-
//!   accessible, perturb/restore/update fan out over element ranges on the
//!   ExecContext worker team with results bitwise identical to the serial
//!   loop for any thread count (same guarantee as optim.zig's parallelMap).
//! - **Member-parallel evaluation.** For parameter sets small enough to
//!   replicate (adapters, MLPs), `materializeMember` writes theta +
//!   sigma*eps_n into caller-owned replica buffers without touching the
//!   shared parameters, and `evaluateMembers` fans the population out over
//!   OS threads — ES's embarrassing parallelism without giving up the
//!   in-place path for big models.
//!
//! Numerics (pinned by the golden tests, generated by
//! tools/gen_es_goldens.py, and cross-checked against the actual reference
//! code by tools/check_es_parity.py): noise is f32; per member the delta
//! `t = sigma * eps` rounds once in f32, narrows to the parameter dtype, and
//! applies widen-add-narrow — the reference's `p.data.add_(sigma*noise)`
//! semantics. Perturb and restore apply the bitwise-same `t`, so `restore`
//! in `.regenerate` mode is exact up to the usual `(x + t) - t` float drift
//! (`.snapshot` mode restores bitwise instead). The update accumulates
//! `C_n * eps_n` in f32 with explicit mul-then-add roundings (no FMA),
//! scales once by `alpha/population`, narrows the delta to the parameter
//! dtype, and adds widen-add-narrow — the reference's fp32 accumulation
//! semantics (`update_accumulator` in f32, `.to(p.dtype)`, in-place add).
//!
//! Checkpoint contract (same rationale as rng.zig): member seeds and noise
//! streams are pure functions of (config.seed, iteration, member, slot) and
//! the scheme knobs (noise, antithetic) through the `gaussianFillAtFast`
//! mapping. Resuming a run from a saved `iteration` regenerates the exact
//! same population; the mappings below may never change once checkpoints
//! exist.
//!
//! Ownership: like optimizers, the trainer retains refcounted views of
//! facade-registered tensors (safe if the facade moves by value), but only
//! BORROWS buffers registered through `addRegistry` — the registry must
//! outlive the trainer. Names are borrowed either way. ES needs no GradState:
//! frozen constants and typed (f16/bf16) tensors are first-class parameters.
//!
//! Ternary genomes (BitNet b1.58-class weights) are a SECOND slot kind:
//! `addTernaryParam` registers borrowed tq2_0 blocks whose 2-bit crumbs
//! (w+1 in {0, 1, 2}) ARE the training state — no latent floats, so every
//! member and every checkpoint is a valid ternary inference model.
//! Perturbation is sparse trit mutation and the update is EGGROLL's
//! vote-and-threshold single-bin integer recipe adapted from int8 to trits:
//! per member, `max(1, round(ternary_flip_rate * len))` clamped one-bin
//! flips regenerated from a counter stream in a dedicated domain
//! (`ternaryMemberSeed`/`ternarySlotStreamSeed` — disjoint from the
//! gaussian domains, so mixed float+ternary trainers share population,
//! rewards, and iteration while float slots stay bitwise unchanged); the
//! update reuses the reward shaping and antithetic fold, accumulates
//! per-index coefficient-weighted votes over the population's flips, and
//! applies the top-K nonzero votes (sorted |vote| desc, index asc — a
//! pinned total order) as one-bin moves toward sign(vote), with
//! K = min(touched, max(1, round(len * ternary_update_fraction /
//! (1 + ternary_update_decay * iteration)))). Clamping at the ternary rails
//! destroys information, so `restore` replays a per-slot (index, old code)
//! undo log in reverse instead of regenerate-subtracting. Block scales
//! (`d`) are never touched. All three ternary knobs and the flip-stream
//! mapping are checkpoint contracts like `antithetic`: a resumed run must
//! re-pass them identically (the trainers' checkpoint state,
//! `fucina_models.train.trainer_state.TrainerState`, does not persist them).
//!
//! Stability: experimental (CHANGELOG.md tiers).
//!
//! Layout: this file is the facade; the bodies live in `es/` (`common`
//! substrate, `slots` float-slot storage, `ternary` genome machinery,
//! `kernels` element kernels, `trainer` the Trainer).

const common = @import("es/common.zig");
const slots = @import("es/slots.zig");
const ternary = @import("es/ternary.zig");
const kernels = @import("es/kernels.zig");
const trainer = @import("es/trainer.zig");

pub const BlockTQ2_0 = common.BlockTQ2_0;
pub const EsError = common.EsError;
pub const NoiseScheme = common.NoiseScheme;
pub const RestoreMode = common.RestoreMode;
pub const AnchorDecay = common.AnchorDecay;
pub const RewardNorm = common.RewardNorm;
pub const Config = common.Config;
pub const Stats = common.Stats;
pub const Trainer = trainer.Trainer;

test {
    _ = common;
    _ = slots;
    _ = ternary;
    _ = kernels;
    _ = trainer;
    _ = @import("es_tests.zig");
}
