//! Evolution Strategies at scale (ES) — gradient-free training over named
//! parameter buffers, after "Evolution Strategies at Scale: LLM Fine-Tuning
//! Beyond Reinforcement Learning" (arXiv:2509.24372; reference implementation
//! github.com/VsonicV/es-at-scale — algorithm reimplemented here from the
//! paper, not ported: the reference code is under a noncommercial Academic
//! Public License).
//!
//! The algorithm is deliberately vanilla OpenAI-ES (Salimans et al. 2017)
//! with the reference's simplifications kept faithfully:
//!
//!     eps_n ~ N(0, I)                                n = 1..population
//!     R_n   = reward(theta + sigma * eps_n)          (forward passes only)
//!     C_n   = (R_n - mean(R)) / (std(R) + 1e-8)      (z-score, ddof = 0)
//!     theta += (alpha / population) * sum_n C_n * eps_n
//!
//! By default: no antithetic pairs, no rank shaping, no optimizer state,
//! and — the reference's documented deviation from the textbook update — NO
//! division by sigma in the update: the 1/sigma factor is folded into alpha
//! (their default alpha = sigma/2). Three extensions are available OPT-IN,
//! clearly beyond the reference: `reward_norm = .centered_ranks`
//! (outlier-immune fitness shaping) and `antithetic = true` (mirrored
//! +/-eps pairs; variance reduction + half the update-side noise
//! regeneration), both from Salimans et al. 2017, and `anchor_decay`
//! (anchored weight decay toward the pretrained parameters, from the same
//! group's arXiv:2605.30148 — see `AnchorDecay`). Rewards are anything the
//! caller can score from a forward pass; this module never sees data,
//! models, or losses.
//!
//! Scale comes from never materializing the population:
//!
//! - **Seed-regenerated noise.** A member's perturbation is a pure function
//!   of (seed, iteration, member, slot, element) through the counter-based
//!   splitmix64 gaussian — the vectorized `rng.gaussianFillAtFast` mapping
//!   (noise regeneration dominates full-parameter ES on CPU) — so perturb,
//!   restore, and update all REGENERATE noise on the fly: nothing of size
//!   O(params) is ever stored beyond the parameters themselves.
//! - **In-place evaluation.** `perturb`/`restore` mutate the registered
//!   buffers directly (the reference's `p.data.add_(sigma*eps)` /
//!   `add_(-sigma*eps)` scheme); one model instance serves the whole
//!   population, evaluated member by member.
//! - **Chunk-parallel kernels.** Because element j's noise is O(1)-random-
//!   accessible, perturb/restore/update fan out over element ranges on the
//!   ExecContext worker team with results bitwise identical to the serial
//!   loop for any thread count (same guarantee as optim.zig's parallelMap).
//! - **Member-parallel evaluation.** For parameter sets small enough to
//!   replicate (adapters, MLPs), `materializeMember` writes theta +
//!   sigma*eps_n into caller-owned replica buffers without touching the
//!   shared parameters, and `evaluateMembers` fans the population out over
//!   OS threads — ES's embarrassing parallelism without giving up the
//!   in-place path for big models.
//!
//! Numerics (pinned by the golden tests, generated by
//! tools/gen_es_goldens.py, and cross-checked against the actual reference
//! code by tools/check_es_parity.py): noise is f32; per member the delta
//! `t = sigma * eps` rounds once in f32, narrows to the parameter dtype, and
//! applies widen-add-narrow — the reference's `p.data.add_(sigma*noise)`
//! semantics. Perturb and restore apply the bitwise-same `t`, so `restore`
//! in `.regenerate` mode is exact up to the usual `(x + t) - t` float drift
//! (`.snapshot` mode restores bitwise instead). The update accumulates
//! `C_n * eps_n` in f32 with explicit mul-then-add roundings (no FMA),
//! scales once by `alpha/population`, narrows the delta to the parameter
//! dtype, and adds widen-add-narrow — the reference's fp32 accumulation
//! semantics (`update_accumulator` in f32, `.to(p.dtype)`, in-place add).
//!
//! Checkpoint contract (same rationale as rng.zig): member seeds and noise
//! streams are pure functions of (config.seed, iteration, member, slot) and
//! the scheme knobs (noise, antithetic) through the `gaussianFillAtFast`
//! mapping. Resuming a run from a saved `iteration` regenerates the exact
//! same population; the mappings below may never change once checkpoints
//! exist.
//!
//! Ownership: like optimizers, the trainer retains refcounted views of
//! facade-registered tensors (safe if the facade moves by value), but only
//! BORROWS buffers registered through `addRegistry` — the registry must
//! outlive the trainer. Names are borrowed either way. ES needs no GradState:
//! frozen constants and typed (f16/bf16) tensors are first-class parameters.
//!
//! Ternary genomes (BitNet b1.58-class weights) are a SECOND slot kind:
//! `addTernaryParam` registers borrowed tq2_0 blocks whose 2-bit crumbs
//! (w+1 in {0, 1, 2}) ARE the training state — no latent floats, so every
//! member and every checkpoint is a valid ternary inference model.
//! Perturbation is sparse trit mutation and the update is EGGROLL's
//! vote-and-threshold single-bin integer recipe adapted from int8 to trits:
//! per member, `max(1, round(ternary_flip_rate * len))` clamped one-bin
//! flips regenerated from a counter stream in a dedicated domain
//! (`ternaryMemberSeed`/`ternarySlotStreamSeed` — disjoint from the
//! gaussian domains, so mixed float+ternary trainers share population,
//! rewards, and iteration while float slots stay bitwise unchanged); the
//! update reuses the reward shaping and antithetic fold, accumulates
//! per-index coefficient-weighted votes over the population's flips, and
//! applies the top-K nonzero votes (sorted |vote| desc, index asc — a
//! pinned total order) as one-bin moves toward sign(vote), with
//! K = min(touched, max(1, round(len * ternary_update_fraction /
//! (1 + ternary_update_decay * iteration)))). Clamping at the ternary rails
//! destroys information, so `restore` replays a per-slot (index, old code)
//! undo log in reverse instead of regenerate-subtracting. Block scales
//! (`d`) are never touched. All three ternary knobs and the flip-stream
//! mapping are checkpoint contracts like `antithetic` (persisted as the
//! `es_ternary_*` TrainerState fields).

const std = @import("std");
const backend_mod = @import("backend.zig");
const dtype_mod = @import("dtype.zig");
const exec_mod = @import("exec.zig");
const parallel = @import("parallel.zig");
const param_registry = @import("param_registry.zig");
const rng = @import("rng.zig");
const thread = @import("thread.zig");

const Allocator = std.mem.Allocator;
const DType = dtype_mod.DType;
const ExecContext = exec_mod.ExecContext;

/// Ternary genome storage unit (GGUF tq2_0, the backend quantized-matmul
/// block): 256 2-bit crumbs storing w+1 in {0, 1, 2} plus one fp16 scale
/// `d` that ES never touches (register scales as float slots to train them).
pub const BlockTQ2_0 = backend_mod.BlockTQ2_0;

pub const EsError = error{
    InvalidConfig,
    AnchorMissing,
    UnsupportedDType,
    NonContiguousParam,
    DuplicateParam,
    NoParams,
    RewardCountMismatch,
    MemberActive,
    MemberNotActive,
    ReplicaShapeMismatch,
};

/// How each member's noise streams relate across parameter slots.
pub const NoiseScheme = enum {
    /// Every (member, slot) pair gets an independent stream — the clean
    /// formulation (the reference archive's "iid" variant).
    iid,
    /// Every slot of a member reuses the SAME stream, so same-length slots
    /// receive identical noise and shorter slots share a prefix — the
    /// reference library's default scheme (an acknowledged artifact of
    /// reseeding one generator per tensor; kept for reference-faithful runs).
    correlated,
};

/// How `restore` undoes a perturbation.
pub const RestoreMode = enum {
    /// Regenerate the noise and subtract (the reference's zero-memory
    /// scheme). Exact up to `(x + t) - t` rounding drift per element.
    regenerate,
    /// Snapshot the parameter bytes on `perturb` and memcpy them back:
    /// bitwise restore, at the cost of one extra copy of the parameters.
    snapshot,
};

/// Anchored weight decay (AWD, arXiv:2605.30148, the ES-at-scale group's
/// anti-forgetting regularizer): a proximal step applied AFTER each ES
/// update, pulling theta toward a fixed ANCHOR (`captureAnchor` — typically
/// the pretrained weights at fine-tuning start; meaningless from scratch,
/// where the anchor would be random init):
///
///     l2: theta <- theta_0 + (1 - alpha*lambda) * (theta - theta_0)
///     l1: theta <- theta_0 + sign(d) * max(|d| - alpha*lambda, 0),
///         d = theta - theta_0   (proximal soft-threshold; induces sparsity)
///
/// The decay step is the COUPLED alpha*lambda (the reference's fixed-alpha
/// form); l2 requires alpha*lambda < 1. Reference defaults: l2 lambda = 10,
/// l1 lambda = 0.01 (with alpha = 5e-4). Counteracts the accumulated
/// random-walk drift in reward-irrelevant directions — the cheap substitute
/// for a large population.
pub const AnchorDecay = enum { none, l1, l2 };

/// Reward shaping applied inside `update`.
pub const RewardNorm = enum {
    /// (r - mean) / (std + 1e-8), stats in f64, ddof = 0 — the reference's
    /// only implemented shaping. Affine, so it PRESERVES outlier magnitude:
    /// one catastrophic member can dominate the update (the classic failure
    /// mode with unbounded rewards such as raw -CE). Self-stops exactly when
    /// every reward ties (all coefficients become 0).
    z_score,
    /// Centered-rank fitness shaping (Salimans et al. 2017, the OpenAI-ES
    /// default; the ES-at-scale reference deliberately drops it): members
    /// are ranked ascending by reward and mapped to the fixed grid
    /// rank/(N-1) - 0.5 in [-0.5, 0.5]. Invariant to any monotone reward
    /// transform and immune to outliers (the worst member is exactly -0.5
    /// no matter how bad). Ties break by MEMBER INDEX, ascending — a pinned,
    /// deterministic order (numpy argsort tie order is implementation-
    /// defined; this mapping is a checkpoint contract). Note: unlike
    /// z_score, all-equal rewards still produce the full utility spread
    /// (a mean-zero phantom step), so pair long runs with eval-based
    /// stopping.
    centered_ranks,
    /// Use raw rewards as coefficients (tests / externally-shaped rewards).
    none,
};

pub const Config = struct {
    /// Perturbation scale. Reference default.
    sigma: f32 = 0.001,
    /// Learning rate with 1/sigma folded in; null = sigma/2 (the reference's
    /// auto default).
    alpha: ?f32 = null,
    /// Population size N. Reference default.
    population: usize = 30,
    /// Mirrored (antithetic) sampling — Salimans et al. 2017's variance
    /// reduction, deliberately stripped by the ES-at-scale reference (kept
    /// opt-in here for the same reason as `centered_ranks`): members pair up
    /// as (+eps, -eps) sharing one noise draw — member 2k draws the stream,
    /// member 2k+1 applies its negation — and the update folds each pair to
    /// (C_2k - C_2k+1) * eps_k, halving update-side noise regeneration.
    /// Requires an even population. Part of the noise checkpoint contract
    /// (persist it alongside seed/population/noise scheme).
    antithetic: bool = false,
    noise: NoiseScheme = .iid,
    restore_mode: RestoreMode = .regenerate,
    /// Cache each iteration's noise streams in RAM: every stream is
    /// regenerated ONCE per iteration (on first use, straight into the
    /// cache) and replayed from memory afterwards — bitwise identical to
    /// regeneration. Memory: n_streams * elementCount * 4 bytes, n_streams
    /// = population (population/2 with antithetic). Pays off only when
    /// replays outnumber fills by enough to beat the cache's allocation and
    /// memory traffic (large populations, small parameter sets); at large
    /// parameter counts the cache can be a net loss — benchmark before
    /// enabling. Replica materialization does not consult the cache.
    cache_streams: bool = false,
    /// AWD penalty (see `AnchorDecay`); `.none` = the reference algorithm.
    anchor_decay: AnchorDecay = .none,
    /// AWD lambda; the applied per-iteration step is alpha * lambda.
    anchor_lambda: f32 = 0,
    reward_norm: RewardNorm = .z_score,
    /// Ternary slots only (`addTernaryParam`): the fraction of a slot's
    /// logical elements each member flips per perturbation — per-member
    /// flips = max(1, round(ternary_flip_rate * len)). Must be in (0, 1].
    /// Part of the flip-stream checkpoint contract like `antithetic`
    /// (persist it alongside seed/population; `es_ternary_flip_rate`).
    ternary_flip_rate: f32 = 0.001,
    /// Ternary update budget: the top-K vote cap per update is
    /// K = max(1, round(effective_fraction * len)). Must be in (0, 1].
    /// Checkpoint contract (`es_ternary_update_fraction`).
    ternary_update_fraction: f32 = 0.005,
    /// Decay schedule on the ternary update budget: effective_fraction =
    /// ternary_update_fraction / (1 + ternary_update_decay * iteration) —
    /// EGGROLL's 1/(1+ct) cadence; 0 = constant budget. Must be finite and
    /// >= 0. Checkpoint contract (`es_ternary_update_decay`).
    ternary_update_decay: f32 = 0.0,
    /// Base seed for the member-seed and noise-stream derivations.
    seed: u64 = 42,
};

/// Per-update reward statistics (pre-normalization, over the population).
pub const Stats = struct {
    mean_reward: f64,
    std_reward: f64,
    min_reward: f32,
    max_reward: f32,
};

/// Domain separators so member-seed and noise-stream derivations never
/// collide with each other or with other rng.at consumers of the same base
/// seed (same pattern as the trainers' dropout domain).
const seed_domain: u64 = 0x65735f7365656473; // "es_seeds"
const noise_domain: u64 = 0x65735f6e6f697365; // "es_noise"
/// Ternary flip streams live in their own domain: a member's flip stream
/// and its gaussian noise streams derive from the same (config.seed,
/// iteration, member) but can never collide, which is what keeps float
/// slots bitwise unchanged when ternary slots join a trainer.
const ternary_domain: u64 = 0x65735f7472697473; // "es_trits"

/// Elementwise noise kernels chunk across the worker pool above this many
/// elements. Noise regeneration is ~an order of magnitude costlier per
/// element than an optimizer step (Box-Muller: two mixes + log/sqrt/cos), so
/// the threshold sits below optim.zig's 1<<17. Every parallel loop here is an
/// element-independent map — results are bitwise identical to the serial
/// path for any thread count.
const perturb_min_len: usize = 1 << 14;
/// The update loop does `population` regenerations per element; its
/// threshold is correspondingly lower.
const update_min_len: usize = 1 << 11;

/// Stack chunk (f32 elements) for the noise/accumulator scratch of the
/// kernels below — small enough for worker stacks, large enough to amortize
/// the per-chunk pair alignment.
const chunk_len: usize = 2048;

pub const Trainer = struct {
    allocator: Allocator,
    config: Config,
    slots: std.ArrayList(Slot) = .empty,
    /// Ternary genome slots (`addTernaryParam`) — kept apart from the float
    /// slots so the float noise-stream enumeration (slot index) never shifts
    /// when ternary slots register (checkpoint contract).
    ternary_slots: std.ArrayList(TernarySlot) = .empty,
    /// Advances once per `update`. Member seeds derive from it — persist it
    /// (e.g. in trainer_state.json) to resume the exact population stream.
    iteration: u64 = 0,
    /// In-place tripwire: the member currently applied to the shared
    /// parameters, if any.
    active_member: ?usize = null,
    /// `.snapshot` restore slab (lazy; concatenated slot bytes).
    snapshot: ?[]u8 = null,
    /// Slab freshness: a snapshot-mode restore leaves theta == slab, so
    /// per-member re-copies are skipped until an update dirties it.
    snapshot_valid: bool = false,
    /// Per-iteration noise-stream cache (see `Config.cache_streams`).
    stream_cache: ?StreamCache = null,
    /// The AWD anchor theta_0 (concatenated slot bytes, dtype-preserved).
    /// Captured ONCE by `captureAnchor` and never refreshed. On GPU builds
    /// it lives in resident bytes so the device anchor kernel can read it.
    anchor: ?[]u8 = null,
    anchor_resident: bool = false,
    /// Ternary-update scratch, trainer-owned so steady-state updates reuse
    /// capacity instead of allocating: the per-slot vote accumulator
    /// (cleared between slots — vote isolation) and the staged top-K entry
    /// lists of every slot for one update, concatenated in slot order
    /// (`TernarySlot.pending` entries per slot).
    ternary_votes: std.AutoHashMapUnmanaged(usize, f32) = .empty,
    ternary_entries: std.ArrayList(VoteEntry) = .empty,

    const Self = @This();

    pub fn init(allocator: Allocator, config: Config) !Self {
        if (!(config.sigma > 0) or !std.math.isFinite(config.sigma)) return EsError.InvalidConfig;
        if (config.alpha) |alpha| {
            if (!(alpha > 0) or !std.math.isFinite(alpha)) return EsError.InvalidConfig;
        }
        if (config.population < 2) return EsError.InvalidConfig;
        if (config.antithetic and config.population % 2 != 0) return EsError.InvalidConfig;
        // `!(x > 0)`/`!(x <= 1)` reject NaN alongside the range violations.
        if (!(config.ternary_flip_rate > 0) or !(config.ternary_flip_rate <= 1)) return EsError.InvalidConfig;
        if (!(config.ternary_update_fraction > 0) or !(config.ternary_update_fraction <= 1)) return EsError.InvalidConfig;
        if (!(config.ternary_update_decay >= 0) or !std.math.isFinite(config.ternary_update_decay)) return EsError.InvalidConfig;
        if (config.anchor_decay != .none) {
            if (!(config.anchor_lambda > 0) or !std.math.isFinite(config.anchor_lambda)) return EsError.InvalidConfig;
            const alpha = config.alpha orelse (config.sigma / 2);
            // The l2 shrink factor (1 - alpha*lambda) must stay positive.
            if (config.anchor_decay == .l2 and !(alpha * config.anchor_lambda < 1)) return EsError.InvalidConfig;
        }
        return .{ .allocator = allocator, .config = config };
    }

    pub fn deinit(self: *Self) void {
        self.ternary_votes.deinit(self.allocator);
        self.ternary_entries.deinit(self.allocator);
        if (self.anchor) |slab| self.freeAnchor(slab);
        if (self.stream_cache) |*cache| cache.deinit(self.allocator);
        if (self.snapshot) |slab| self.allocator.free(slab);
        for (self.slots.items) |*slot| slot.deinit(self.allocator);
        self.slots.deinit(self.allocator);
        for (self.ternary_slots.items) |*slot| slot.deinit(self.allocator);
        self.ternary_slots.deinit(self.allocator);
        self.* = undefined;
    }

    /// The effective learning rate: `config.alpha`, defaulting to sigma/2.
    pub fn alphaValue(self: *const Self) f32 {
        return self.config.alpha orelse (self.config.sigma / 2);
    }

    /// Register one f32/f16/bf16 facade tensor (autograd variable, constant,
    /// or grad-free typed tensor — ES treats them all the same). Retains a
    /// refcounted storage view; `name` (optional) is borrowed.
    pub fn addParam(self: *Self, t: anytype) !void {
        try self.addParamNamed(t, null);
    }

    pub fn addParamNamed(self: *Self, t: anytype, name: ?[]const u8) !void {
        const T = comptime validateFacadePtr(@TypeOf(t));
        if (!t.value.isContiguous()) return EsError.NonContiguousParam;

        const Raw = @TypeOf(t.value);
        const retained = try self.allocator.create(Raw);
        {
            errdefer self.allocator.destroy(retained);
            retained.* = try t.value.cloneView();
        }
        // From here the retained view is owned by the slot value: addSlot
        // releases it through `release` on any failure path.
        try self.addSlot(.{
            .name = name,
            .dtype = T.dtype,
            .bytes = std.mem.sliceAsBytes(retained.data()),
            .n = retained.len(),
            .retained = retained,
            .release = makeRelease(Raw),
        });
    }

    /// Register every entry of a `ParamRegistry` — trainable AND frozen
    /// (ES needs no gradients, so frozen f16/bf16 model weights qualify).
    /// Buffers and names are BORROWED: the registry must outlive the trainer.
    /// Entries whose storage is already registered are SKIPPED, not rejected:
    /// tied weights (e.g. a tied output/embedding matrix collected under two
    /// paths) perturb once, matching torch named_parameters() deduplication.
    /// Returns the number of slots actually added.
    pub fn addRegistry(self: *Self, registry: *const param_registry.ParamRegistry) !usize {
        var added: usize = 0;
        entries: for (0..registry.parameterCount()) |i| {
            const entry = registry.view(i);
            const n = switch (entry.dtype) {
                inline .f32, .f16, .bf16 => |dt| entry.bytes.len / @sizeOf(dtype_mod.Scalar(dt)),
                else => return EsError.UnsupportedDType,
            };
            for (self.slots.items) |*existing| {
                if (existing.bytes.ptr == entry.bytes.ptr) continue :entries;
            }
            try self.addSlot(.{
                .name = entry.name,
                .dtype = entry.dtype,
                .bytes = entry.bytes,
                .n = n,
                .retained = null,
                .release = null,
            });
            added += 1;
        }
        return added;
    }

    /// Register one ternary genome. `blocks` are BORROWED mutable storage
    /// (they must outlive the trainer) holding `len` logical elements as
    /// 2-bit crumbs: `len` must be a positive multiple of 256 with
    /// blocks.len == len/256, and every crumb must be a valid ternary code
    /// (0/1/2). Crumb code 3 — unrepresentable by the encoders, possible in
    /// a corrupt or untrusted GGUF — is rejected here so it can never reach
    /// the flip/vote machinery; `len` is whole blocks, so the scan has no
    /// partial-block tail to exempt. The blocks themselves are the training
    /// state; `d` scales are never touched. Ternary slots do not participate
    /// in snapshots, stream caches, or anchored weight decay (all float-slot
    /// machinery) — their restore path is the per-slot undo log.
    pub fn addTernaryParam(self: *Self, blocks: []BlockTQ2_0, len: usize) !void {
        try self.addTernaryParamNamed(blocks, len, null);
    }

    pub fn addTernaryParamNamed(self: *Self, blocks: []BlockTQ2_0, len: usize, name: ?[]const u8) !void {
        // Same tripwire as addSlot: the active member's undo logs describe
        // the slot set at perturb time.
        if (self.active_member != null) return EsError.MemberActive;
        if (len == 0 or len % ternary_block_len != 0) return EsError.InvalidConfig;
        if (blocks.len != len / ternary_block_len) return EsError.InvalidConfig;
        for (self.ternary_slots.items) |*existing| {
            if (existing.blocks.ptr == blocks.ptr) return EsError.DuplicateParam;
        }
        // Reject crumb code 3 up front: a byte holds one in some lane iff
        // both bits of a pair are set. len % 256 == 0 (checked above) makes
        // every stored crumb logical, so the scan is whole-block.
        for (blocks) |*block| {
            for (block.qs) |byte| {
                if (byte & (byte >> 1) & 0x55 != 0) return EsError.InvalidConfig;
            }
        }
        // The undo log is sized ONCE at the fixed per-member flip count.
        const undo = try self.allocator.alloc(UndoEntry, self.ternaryFlipCount(len));
        errdefer self.allocator.free(undo);
        try self.ternary_slots.append(self.allocator, .{
            .name = name,
            .blocks = blocks,
            .len = len,
            .undo = undo,
        });
    }

    /// Snapshot the CURRENT parameters as the AWD anchor theta_0. Call once
    /// after registration, while the parameters still hold the values the
    /// decay should pull toward (pretrained weights / initial adapters) —
    /// in particular BEFORE loading a training checkpoint on resume, so the
    /// anchor stays the initial model rather than the resumed one. Required
    /// before `update` when `anchor_decay != .none`. AWD is a float-slot
    /// regularizer: a ternary-only trainer captures an EMPTY slab (genomes
    /// restore through undo logs, not anchors) and the decay step in
    /// `update` no-ops over its zero float slots; NoParams only when no
    /// slot of either kind is registered.
    pub fn captureAnchor(self: *Self) !void {
        if (self.active_member != null) return EsError.MemberActive;
        if (self.slots.items.len == 0 and self.ternary_slots.items.len == 0) return EsError.NoParams;
        var total: usize = 0;
        for (self.slots.items) |*slot| total += slot.bytes.len;
        if (self.anchor == null) {
            self.anchor = blk: {
                if (comptime backend_mod.gpu_impl.enabled) {
                    // A ternary-only (zero-length) slab needs no device
                    // residency.
                    if (total > 0) {
                        if (backend_mod.gpu_impl.allocResidentBytes(total)) |dev| {
                            self.anchor_resident = true;
                            break :blk dev;
                        }
                    }
                }
                break :blk try self.allocator.alloc(u8, total);
            };
        }
        const slab = self.anchor.?;
        var offset: usize = 0;
        for (self.slots.items) |*slot| {
            @memcpy(slab[offset..][0..slot.bytes.len], slot.bytes);
            offset += slot.bytes.len;
        }
    }

    fn addSlot(self: *Self, slot: Slot) !void {
        errdefer if (slot.retained) |retained| slot.release.?(retained, self.allocator);
        // Same tripwire as perturb/update: growing the parameter set while a
        // member is applied in place would make the eventual restore subtract
        // noise the new slot never received (.regenerate) or invalidate the
        // live snapshot slab (.snapshot).
        if (self.active_member != null) return EsError.MemberActive;
        switch (slot.dtype) {
            .f32, .f16, .bf16 => {},
            else => return EsError.UnsupportedDType,
        }
        for (self.slots.items) |*existing| {
            if (existing.bytes.ptr == slot.bytes.ptr) return EsError.DuplicateParam;
        }
        if (self.snapshot) |slab| {
            // The lazy slab is sized to the slots present at first perturb;
            // growing the parameter set afterwards would silently corrupt
            // snapshot restores, so re-size it eagerly here.
            self.allocator.free(slab);
            self.snapshot = null;
            self.snapshot_valid = false;
        }
        if (self.stream_cache) |*cache| {
            // Same sizing argument as the snapshot slab.
            cache.deinit(self.allocator);
            self.stream_cache = null;
        }
        if (self.anchor) |slab| {
            // A stale anchor would silently decay the new slot toward
            // garbage; force a fresh captureAnchor.
            self.freeAnchor(slab);
            self.anchor = null;
        }
        try self.slots.append(self.allocator, slot);
    }

    pub fn paramCount(self: *const Self) usize {
        return self.slots.items.len + self.ternary_slots.items.len;
    }

    pub fn elementCount(self: *const Self) usize {
        var n: usize = 0;
        for (self.slots.items) |*slot| n += slot.n;
        for (self.ternary_slots.items) |*slot| n += slot.len;
        return n;
    }

    /// The seed of population member `member` at the CURRENT iteration — a
    /// pure function of (config.seed, iteration, member). Checkpoint
    /// contract; see the module doc.
    pub fn memberSeed(self: *const Self, member: usize) u64 {
        return rng.at(
            self.config.seed ^ seed_domain,
            self.iteration *% @as(u64, self.config.population) +% @as(u64, member),
        );
    }

    /// The member whose seed drives `member`'s noise: itself, or — under
    /// antithetic sampling — the even member of its (+, -) pair.
    fn noiseMemberIndex(self: *const Self, member: usize) usize {
        return if (self.config.antithetic) member & ~@as(usize, 1) else member;
    }

    /// +1 for members applying their pair's draw, -1 for the mirrored twin.
    fn noiseSign(self: *const Self, member: usize) f32 {
        return if (self.config.antithetic and member % 2 == 1) -1 else 1;
    }

    /// The noise-stream seed of (member, slot) under the configured scheme.
    fn slotStreamSeed(self: *const Self, member_seed: u64, slot_index: usize) u64 {
        return switch (self.config.noise) {
            .iid => rng.at(member_seed ^ noise_domain, slot_index),
            .correlated => member_seed,
        };
    }

    /// The ternary flip seed of member `member` at the CURRENT iteration —
    /// `memberSeed`'s twin in the dedicated ternary domain. Checkpoint
    /// contract; see the module doc.
    pub fn ternaryMemberSeed(self: *const Self, member: usize) u64 {
        return rng.at(
            self.config.seed ^ ternary_domain,
            self.iteration *% @as(u64, self.config.population) +% @as(u64, member),
        );
    }

    /// Ternary slot `slot_index`'s flip stream for a ternary member seed —
    /// always per-slot (the `noise` scheme governs gaussian slots only).
    /// Flip i of the stream reads index = at(seed, 2i) % len and a delta
    /// bit at(seed, 2i+1) & 1 (1 = +1, 0 = -1); the antithetic odd member
    /// negates the deltas of its pair's stream. Checkpoint contract.
    pub fn ternarySlotStreamSeed(member_seed: u64, slot_index: usize) u64 {
        return rng.at(member_seed ^ ternary_domain, slot_index);
    }

    /// Flips per member on a ternary slot of `len` logical elements:
    /// max(1, round(ternary_flip_rate * len)).
    pub fn ternaryFlipCount(self: *const Self, len: usize) usize {
        const raw = @round(@as(f64, self.config.ternary_flip_rate) * @as(f64, @floatFromInt(len)));
        return @max(1, @as(usize, @intFromFloat(raw)));
    }

    /// theta += sigma * eps_member, in place over every registered slot
    /// (chunk-parallel). Exactly one member may be active at a time.
    pub fn perturb(self: *Self, ctx: *ExecContext, member: usize) !void {
        if (self.active_member != null) return EsError.MemberActive;
        if (self.slots.items.len == 0 and self.ternary_slots.items.len == 0) return EsError.NoParams;
        if (self.config.restore_mode == .snapshot and !self.snapshot_valid) {
            try self.takeSnapshot();
            self.snapshot_valid = true;
        }
        try self.applySigned(ctx, member, 1.0);
        self.perturbTernary(member);
        self.active_member = member;
    }

    /// Undo `perturb(member)`: regenerate-subtract (`.regenerate`) or memcpy
    /// the snapshot back (`.snapshot`); ternary slots always replay their
    /// undo logs (bitwise, either mode).
    pub fn restore(self: *Self, ctx: *ExecContext, member: usize) !void {
        const active = self.active_member orelse return EsError.MemberNotActive;
        if (active != member) return EsError.MemberNotActive;
        switch (self.config.restore_mode) {
            .regenerate => try self.applySigned(ctx, member, -1.0),
            .snapshot => {
                const slab = self.snapshot.?;
                var offset: usize = 0;
                for (self.slots.items) |*slot| {
                    @memcpy(slot.bytes, slab[offset..][0..slot.bytes.len]);
                    offset += slot.bytes.len;
                }
            },
        }
        self.restoreTernary();
        self.active_member = null;
    }

    /// Apply `member`'s sparse trit flips to every ternary slot, recording
    /// (index, old code) per flip: clamping at the rails is lossy, so exact
    /// restore replays the log in reverse (regenerate-subtract cannot work).
    fn perturbTernary(self: *Self, member: usize) void {
        if (self.ternary_slots.items.len == 0) return;
        const t_seed = self.ternaryMemberSeed(self.noiseMemberIndex(member));
        const mirror = self.config.antithetic and member % 2 == 1;
        for (self.ternary_slots.items, 0..) |*slot, k| {
            const stream_seed = ternarySlotStreamSeed(t_seed, k);
            slot.undo_len = 0;
            for (0..self.ternaryFlipCount(slot.len)) |i| {
                const flip = ternaryFlipAt(stream_seed, @intCast(i), slot.len, mirror);
                const old = crumbGet(slot.blocks, flip.index);
                slot.undo[slot.undo_len] = .{ .index = flip.index, .code = old };
                slot.undo_len += 1;
                crumbSet(slot.blocks, flip.index, moveCode(old, flip.delta));
            }
        }
    }

    /// Replay every ternary slot's undo log in reverse — bitwise restore
    /// (colliding flips on one index unwind through their intermediates).
    fn restoreTernary(self: *Self) void {
        for (self.ternary_slots.items) |*slot| {
            var i = slot.undo_len;
            while (i > 0) {
                i -= 1;
                crumbSet(slot.blocks, slot.undo[i].index, slot.undo[i].code);
            }
            slot.undo_len = 0;
        }
    }

    fn freeAnchor(self: *Self, slab: []u8) void {
        if (comptime backend_mod.gpu_impl.enabled) {
            if (self.anchor_resident) {
                backend_mod.gpu_impl.freeResidentBytes(slab);
                self.anchor_resident = false;
                return;
            }
        }
        self.allocator.free(slab);
    }

    fn takeSnapshot(self: *Self) !void {
        var total: usize = 0;
        for (self.slots.items) |*slot| total += slot.bytes.len;
        if (self.snapshot == null) self.snapshot = try self.allocator.alloc(u8, total);
        const slab = self.snapshot.?;
        var offset: usize = 0;
        for (self.slots.items) |*slot| {
            @memcpy(slab[offset..][0..slot.bytes.len], slot.bytes);
            offset += slot.bytes.len;
        }
    }

    fn applySigned(self: *Self, ctx: *ExecContext, member: usize, sign: f32) !void {
        const member_seed = self.memberSeed(self.noiseMemberIndex(member));
        const scaled = sign * self.noiseSign(member) * self.config.sigma;
        const stream = self.streamIndex(member);
        const region = try self.cacheRegionForStream(stream);
        for (self.slots.items, 0..) |*slot, k| {
            const stream_seed = self.slotStreamSeed(member_seed, k);
            switch (slot.dtype) {
                inline .f32, .f16, .bf16 => |dt| perturbSlot(
                    dt,
                    ctx,
                    slot.elems(dt),
                    stream_seed,
                    scaled,
                    if (region) |r| .{ .data = r.slotRegion(self, k), .filled = r.filled } else null,
                ),
                else => unreachable, // addSlot rejects other dtypes
            }
        }
        if (region) |r| self.stream_cache.?.filled[r.stream] = true;
    }

    /// The noise-stream index a member draws: itself, or its antithetic
    /// pair (member/2) — matches `update`'s stream enumeration.
    fn streamIndex(self: *const Self, member: usize) usize {
        return if (self.config.antithetic) member / 2 else member;
    }

    fn streamCount(self: *const Self) usize {
        return if (self.config.antithetic) self.config.population / 2 else self.config.population;
    }

    const CacheRegion = struct {
        stream: usize,
        base: usize,
        filled: bool,

        fn slotRegion(self: CacheRegion, trainer: *const Trainer, slot_index: usize) []f32 {
            const cache = &trainer.stream_cache.?;
            const offset = cache.slot_offsets[slot_index];
            const len = cache.slot_offsets[slot_index + 1] - offset;
            return cache.data[self.base + offset ..][0..len];
        }
    };

    /// The cache region of `stream` for this iteration (null when caching
    /// is off). Allocates the cache lazily on first use.
    fn cacheRegionForStream(self: *Self, stream: usize) !?CacheRegion {
        if (!self.config.cache_streams) return null;
        if (self.stream_cache == null) {
            self.stream_cache = try StreamCache.init(self.allocator, self.slots.items, self.streamCount());
        }
        const cache = &self.stream_cache.?;
        return .{
            .stream = stream,
            .base = stream * cache.total_elems,
            .filled = cache.filled[stream],
        };
    }

    /// Write theta + sigma * eps_member into caller-owned replica buffers
    /// WITHOUT touching the shared parameters: `dst[k]` receives slot k's
    /// perturbed bytes (lengths must match registration order exactly).
    /// Serial on purpose — member-level parallelism comes from calling this
    /// for different members on different threads (`evaluateMembers`), which
    /// is safe while no member is in-place active.
    pub fn materializeMember(self: *const Self, member: usize, dst: []const []u8) !void {
        if (self.active_member != null) return EsError.MemberActive;
        if (dst.len != self.slots.items.len) return EsError.ReplicaShapeMismatch;
        const member_seed = self.memberSeed(self.noiseMemberIndex(member));
        const scaled = self.noiseSign(member) * self.config.sigma;
        for (self.slots.items, dst, 0..) |*slot, dst_bytes, k| {
            if (dst_bytes.len != slot.bytes.len) return EsError.ReplicaShapeMismatch;
            const stream_seed = self.slotStreamSeed(member_seed, k);
            switch (slot.dtype) {
                inline .f32, .f16, .bf16 => |dt| materializeSlot(
                    dt,
                    slot.elemsConst(dt),
                    // Replica buffers must be Scalar(dtype)-aligned (allocate
                    // them as typed slices, not raw bytes).
                    @alignCast(std.mem.bytesAsSlice(dtype_mod.Scalar(dt), dst_bytes)),
                    stream_seed,
                    scaled,
                ),
                else => unreachable,
            }
        }
    }

    /// Ternary twin of `materializeMember`: copy each ternary slot's blocks
    /// into caller-owned replicas (`dst[k]` = ternary slot k in registration
    /// order, block counts must match) and apply `member`'s flips there,
    /// without touching the shared genome. Mixed float+ternary replicas
    /// call both materializers.
    pub fn materializeTernaryMember(self: *const Self, member: usize, dst: []const []BlockTQ2_0) !void {
        if (self.active_member != null) return EsError.MemberActive;
        if (dst.len != self.ternary_slots.items.len) return EsError.ReplicaShapeMismatch;
        const t_seed = self.ternaryMemberSeed(self.noiseMemberIndex(member));
        const mirror = self.config.antithetic and member % 2 == 1;
        for (self.ternary_slots.items, dst, 0..) |*slot, dst_blocks, k| {
            if (dst_blocks.len != slot.blocks.len) return EsError.ReplicaShapeMismatch;
            @memcpy(dst_blocks, slot.blocks);
            const stream_seed = ternarySlotStreamSeed(t_seed, k);
            for (0..self.ternaryFlipCount(slot.len)) |i| {
                const flip = ternaryFlipAt(stream_seed, @intCast(i), slot.len, mirror);
                crumbSet(dst_blocks, flip.index, moveCode(crumbGet(dst_blocks, flip.index), flip.delta));
            }
        }
    }

    /// One ES update from the population's rewards (`rewards[n]` = member
    /// n's reward at the current iteration): normalize, regenerate every
    /// member's noise, apply `theta += (alpha/population) * sum_n C_n *
    /// eps_n` (chunk-parallel, fp32 accumulation), then advance `iteration`.
    /// Mutate-last: every fallible step (validation, scratch allocation, the
    /// ternary vote collection) runs before the first parameter byte
    /// changes, so a failed update is a no-op — theta, the genomes,
    /// `iteration`, and the snapshot slab all stay consistent.
    pub fn update(self: *Self, ctx: *ExecContext, rewards: []const f32) !Stats {
        if (self.active_member != null) return EsError.MemberActive;
        if (self.slots.items.len == 0 and self.ternary_slots.items.len == 0) return EsError.NoParams;
        if (rewards.len != self.config.population) return EsError.RewardCountMismatch;
        // AWD precondition, checked up front (mutate-last); the slab itself
        // is read only after the ES update applies.
        const anchor_slab: ?[]u8 = if (self.config.anchor_decay != .none)
            self.anchor orelse return EsError.AnchorMissing
        else
            null;

        const stats = rewardStats(rewards);
        const coeffs = try self.allocator.alloc(f32, rewards.len);
        defer self.allocator.free(coeffs);
        switch (self.config.reward_norm) {
            .z_score => for (coeffs, rewards) |*c, r| {
                c.* = @floatCast((@as(f64, r) - stats.mean_reward) / (stats.std_reward + 1e-8));
            },
            .centered_ranks => {
                const order = try self.allocator.alloc(usize, rewards.len);
                defer self.allocator.free(order);
                for (order, 0..) |*member, i| member.* = i;
                // Ascending by (reward, member index): the index tiebreak
                // makes the comparator a total order, so the sort result —
                // and therefore the coefficients — are deterministic.
                std.mem.sort(usize, order, rewards, struct {
                    fn lessThan(r: []const f32, a: usize, b: usize) bool {
                        if (r[a] != r[b]) return r[a] < r[b];
                        return a < b;
                    }
                }.lessThan);
                const denom: f32 = @floatFromInt(rewards.len - 1);
                for (order, 0..) |member, rank| {
                    coeffs[member] = @as(f32, @floatFromInt(rank)) / denom - 0.5;
                }
            },
            .none => @memcpy(coeffs, rewards),
        }

        // Antithetic pairs fold to one stream each: (+eps, -eps) with
        // coefficients C_2k and C_2k+1 contribute (C_2k - C_2k+1) * eps_k —
        // the OpenAI-starter pair-difference form — halving update-side
        // noise regeneration. Division stays by the FULL population (the
        // starter's `g /= returns_n2.size`).
        const n_streams = if (self.config.antithetic) rewards.len / 2 else rewards.len;
        const stream_coeffs = try self.allocator.alloc(f32, n_streams);
        defer self.allocator.free(stream_coeffs);
        if (self.config.antithetic) {
            for (stream_coeffs, 0..) |*c, k| c.* = coeffs[2 * k] - coeffs[2 * k + 1];
        } else {
            @memcpy(stream_coeffs, coeffs);
        }

        const member_seeds = try self.allocator.alloc(u64, n_streams);
        defer self.allocator.free(member_seeds);
        for (member_seeds, 0..) |*seed, k| {
            seed.* = self.memberSeed(if (self.config.antithetic) 2 * k else k);
        }

        const stream_seeds = try self.allocator.alloc(u64, n_streams);
        defer self.allocator.free(stream_seeds);

        // Per-stream cache regions (updateSlot iterates members innermost,
        // so regions travel as parallel slices; null when caching is off).
        var cache_regions: ?[]CacheRegion = null;
        defer if (cache_regions) |regions| self.allocator.free(regions);
        if (self.config.cache_streams) {
            const regions = try self.allocator.alloc(CacheRegion, n_streams);
            errdefer self.allocator.free(regions);
            for (regions, 0..) |*region, stream| {
                region.* = (try self.cacheRegionForStream(stream)).?;
            }
            cache_regions = regions;
        }

        // Ternary slots vote on the SAME folded stream coefficients, so
        // mixed trainers keep one reward pipeline. Collection is the LAST
        // fallible step of the update; the staged moves apply infallibly
        // after the float slots.
        try self.collectTernaryVotes(stream_coeffs);

        const scale = self.alphaValue() / @as(f32, @floatFromInt(self.config.population));
        for (self.slots.items, 0..) |*slot, k| {
            for (stream_seeds, member_seeds) |*stream, member_seed| {
                stream.* = self.slotStreamSeed(member_seed, k);
            }
            switch (slot.dtype) {
                inline .f32, .f16, .bf16 => |dt| updateSlot(
                    dt,
                    ctx,
                    slot.elems(dt),
                    stream_seeds,
                    stream_coeffs,
                    scale,
                    if (cache_regions) |regions| .{ .trainer = self, .slot_index = k, .regions = regions } else null,
                ),
                else => unreachable,
            }
        }
        if (cache_regions) |regions| {
            for (regions) |region| self.stream_cache.?.filled[region.stream] = true;
        }

        self.applyTernaryVotes();

        // AWD (Eq. 4 / Algorithm 1 line 9 of arXiv:2605.30148): the proximal
        // pull toward the anchor reads the POST-update theta and applies the
        // coupled step alpha * lambda, elementwise over every FLOAT
        // parameter (a no-op over zero float slots — ternary-only trainers).
        if (anchor_slab) |slab| {
            const decay_step = self.alphaValue() * self.config.anchor_lambda;
            var offset: usize = 0;
            for (self.slots.items) |*slot| {
                switch (slot.dtype) {
                    inline .f32, .f16, .bf16 => |dt| anchorSlot(
                        dt,
                        ctx,
                        slot.elems(dt),
                        @alignCast(std.mem.bytesAsSlice(dtype_mod.Scalar(dt), slab[offset..][0..slot.bytes.len])),
                        decay_step,
                        self.config.anchor_decay,
                    ),
                    else => unreachable,
                }
                offset += slot.bytes.len;
            }
        }

        self.iteration += 1;
        // The cache holds THIS iteration's streams; the next iteration draws
        // fresh ones. Theta changed, so a snapshot-mode slab is stale too.
        if (self.stream_cache) |*cache| @memset(cache.filled, false);
        self.snapshot_valid = false;
        return stats;
    }

    /// Fallible half of the ternary vote-and-threshold update (EGGROLL's
    /// single-bin integer recipe on trits), run BEFORE any parameter
    /// mutation: regenerate every stream's flips, accumulate vote[index] +=
    /// coeff * delta (colliding flips accumulate; under the antithetic fold
    /// the odd member's mirrored deltas contribute (C+ - C-) * delta_even,
    /// exactly like the gaussian fold, so only the even member's stream
    /// regenerates), then stage each slot's top-K nonzero votes in
    /// `ternary_entries` (`slot.pending` entries per slot, in application
    /// order). Hashmap iteration order is nondeterministic, so votes are
    /// collected and sorted by (|vote| desc, index asc) — a pinned total
    /// order (checkpoint contract); the f32 vote sums themselves accumulate
    /// in fixed stream-then-flip order. K = min(touched, max(1, round(len *
    /// effective_fraction))) per slot, effective_fraction =
    /// ternary_update_fraction / (1 + ternary_update_decay * iteration).
    /// The vote/entry containers are trainer-owned scratch (capacity
    /// retained across updates), so steady-state updates stop allocating.
    fn collectTernaryVotes(self: *Self, stream_coeffs: []const f32) !void {
        self.ternary_entries.clearRetainingCapacity();
        if (self.ternary_slots.items.len == 0) return;
        const eff = @as(f64, self.config.ternary_update_fraction) /
            (1.0 + @as(f64, self.config.ternary_update_decay) * @as(f64, @floatFromInt(self.iteration)));
        for (self.ternary_slots.items, 0..) |*slot, k| {
            self.ternary_votes.clearRetainingCapacity();
            const flips = self.ternaryFlipCount(slot.len);
            for (stream_coeffs, 0..) |coeff, stream| {
                const member = if (self.config.antithetic) 2 * stream else stream;
                const stream_seed = ternarySlotStreamSeed(self.ternaryMemberSeed(member), k);
                // Flips whose one-bin move clamped to a no-op at perturb
                // time still vote — the EGGROLL integer recipe counts them.
                // A possible future refinement is filtering votes where
                // moveCode(current, delta) == current.
                for (0..flips) |i| {
                    const flip = ternaryFlipAt(stream_seed, @intCast(i), slot.len, false);
                    const gop = try self.ternary_votes.getOrPut(self.allocator, flip.index);
                    if (!gop.found_existing) gop.value_ptr.* = 0;
                    gop.value_ptr.* += coeff * @as(f32, @floatFromInt(flip.delta));
                }
            }
            const base = self.ternary_entries.items.len;
            var it = self.ternary_votes.iterator();
            while (it.next()) |kv| {
                if (kv.value_ptr.* != 0) {
                    try self.ternary_entries.append(self.allocator, .{ .index = kv.key_ptr.*, .vote = kv.value_ptr.* });
                }
            }
            std.mem.sort(VoteEntry, self.ternary_entries.items[base..], {}, voteBefore);
            const cap = @max(1, @as(usize, @intFromFloat(@round(eff * @as(f64, @floatFromInt(slot.len))))));
            const kept = @min(self.ternary_entries.items.len - base, cap);
            self.ternary_entries.shrinkRetainingCapacity(base + kept);
            slot.pending = kept;
        }
    }

    /// Infallible half: apply each slot's staged top-K votes as clamped
    /// one-bin moves toward sign(vote), consuming `ternary_entries` in the
    /// exact order `collectTernaryVotes` staged them (slot order, |vote|
    /// desc / index asc within a slot).
    fn applyTernaryVotes(self: *Self) void {
        var offset: usize = 0;
        for (self.ternary_slots.items) |*slot| {
            for (self.ternary_entries.items[offset..][0..slot.pending]) |entry| {
                const delta: i8 = if (entry.vote > 0) 1 else -1;
                crumbSet(slot.blocks, entry.index, moveCode(crumbGet(slot.blocks, entry.index), delta));
            }
            offset += slot.pending;
            slot.pending = 0;
        }
    }

    /// The sequential in-place driver: for each member, perturb → evaluate →
    /// restore; then one `update`. `evaluator` is duck-typed over
    /// `eval(member: usize) !f32` (capture the model/data/ctx it needs).
    pub fn step(self: *Self, ctx: *ExecContext, evaluator: anytype) !Stats {
        const rewards = try self.allocator.alloc(f32, self.config.population);
        defer self.allocator.free(rewards);
        for (rewards, 0..) |*reward, member| {
            try self.perturb(ctx, member);
            const value = evaluator.eval(member) catch |err| {
                // Leave theta unperturbed on the way out; the tripwire state
                // is consistent for a retry.
                try self.restore(ctx, member);
                return err;
            };
            try self.restore(ctx, member);
            reward.* = value;
        }
        return self.update(ctx, rewards);
    }

    /// Member-parallel evaluation over OS threads: workers pull member
    /// indices from a shared counter and call `evaluator.evalMember(worker,
    /// member) !f32` — `worker` (< `workers`) selects the caller's replica
    /// (populate it via `materializeMember`). `workers` must be >= 1 (it is
    /// clamped to the population and a 64-thread ceiling, so the `worker <
    /// workers` bound always holds for replica tables sized by `workers`).
    /// The evaluator must be thread-safe across distinct workers; the shared
    /// parameters are only READ here (no member may be in-place active). The
    /// first error stops the fan-out and is returned after every worker has
    /// joined.
    pub fn evaluateMembers(self: *const Self, evaluator: anytype, rewards: []f32, workers: usize) !void {
        if (workers == 0) return EsError.InvalidConfig;
        if (self.active_member != null) return EsError.MemberActive;
        if (rewards.len != self.config.population) return EsError.RewardCountMismatch;
        const max_workers = 64; // spawned-thread array bound below
        const worker_count = @min(@min(workers, self.config.population), max_workers);
        if (worker_count == 1) {
            for (rewards, 0..) |*reward, member| reward.* = try evaluator.evalMember(0, member);
            return;
        }

        const Evaluator = @TypeOf(evaluator);
        const Shared = struct {
            evaluator: Evaluator,
            rewards: []f32,
            next: std.atomic.Value(usize) = .init(0),
            failed: std.atomic.Value(bool) = .init(false),
            err_mutex: thread.Mutex = .{},
            err: ?anyerror = null,

            fn run(shared: *@This(), worker: usize) void {
                while (!shared.failed.load(.acquire)) {
                    const member = shared.next.fetchAdd(1, .monotonic);
                    if (member >= shared.rewards.len) return;
                    const value = shared.evaluator.evalMember(worker, member) catch |err| {
                        shared.err_mutex.lock();
                        if (shared.err == null) shared.err = err;
                        shared.err_mutex.unlock();
                        shared.failed.store(true, .release);
                        return;
                    };
                    shared.rewards[member] = value;
                }
            }
        };

        var shared = Shared{ .evaluator = evaluator, .rewards = rewards };
        var threads: [64]std.Thread = undefined;
        var spawned: usize = 0;
        // Workers 1..worker_count on spawned threads; worker 0 runs here.
        while (spawned + 1 < worker_count) : (spawned += 1) {
            threads[spawned] = std.Thread.spawn(.{}, Shared.run, .{ &shared, spawned + 1 }) catch break;
        }
        Shared.run(&shared, 0);
        for (threads[0..spawned]) |worker_thread| worker_thread.join();
        if (shared.err) |err| return err;
    }
};

/// Pre-normalization reward statistics: mean/std in f64 (ddof = 0), the
/// reference's float64 numpy stats — with plain SEQUENTIAL summation, which
/// may differ from numpy's pairwise summation in the last f64 ulp at larger
/// populations (invisible after the f32 coefficient cast; the golden
/// generator and parity checker compute their stats sequentially to match).
fn rewardStats(rewards: []const f32) Stats {
    var mean: f64 = 0;
    var min_reward: f32 = rewards[0];
    var max_reward: f32 = rewards[0];
    for (rewards) |r| {
        mean += @as(f64, r);
        min_reward = @min(min_reward, r);
        max_reward = @max(max_reward, r);
    }
    mean /= @floatFromInt(rewards.len);
    var variance: f64 = 0;
    for (rewards) |r| {
        const d = @as(f64, r) - mean;
        variance += d * d;
    }
    variance /= @floatFromInt(rewards.len);
    return .{
        .mean_reward = mean,
        .std_reward = @sqrt(variance),
        .min_reward = min_reward,
        .max_reward = max_reward,
    };
}

/// Per-iteration noise-stream cache (`Config.cache_streams`): stream-major
/// f32 storage — stream s's slot k lives at
/// data[s * total_elems + slot_offsets[k] ..][0 .. slot k len] — plus a
/// per-stream filled flag for the current iteration. Values are exactly the
/// regenerated ones (the kernels regenerate INTO the cache on first use),
/// so cached and uncached runs are bitwise identical.
const StreamCache = struct {
    data: []f32,
    filled: []bool,
    /// Prefix sums of slot element counts (len = n_slots + 1).
    slot_offsets: []usize,
    total_elems: usize,

    fn init(allocator: Allocator, slots: []const Slot, n_streams: usize) !StreamCache {
        const slot_offsets = try allocator.alloc(usize, slots.len + 1);
        errdefer allocator.free(slot_offsets);
        var total: usize = 0;
        for (slots, 0..) |*slot, k| {
            slot_offsets[k] = total;
            total += slot.n;
        }
        slot_offsets[slots.len] = total;
        const data = try allocator.alloc(f32, n_streams * total);
        errdefer allocator.free(data);
        const filled = try allocator.alloc(bool, n_streams);
        @memset(filled, false);
        return .{ .data = data, .filled = filled, .slot_offsets = slot_offsets, .total_elems = total };
    }

    fn deinit(self: *StreamCache, allocator: Allocator) void {
        allocator.free(self.filled);
        allocator.free(self.data);
        allocator.free(self.slot_offsets);
        self.* = undefined;
    }
};

const Slot = struct {
    name: ?[]const u8, // borrowed
    dtype: DType,
    bytes: []u8, // mutable view aliasing the parameter storage
    n: usize,
    retained: ?*anyopaque, // *TensorOf(dtype) for facade-registered slots
    release: ?*const fn (*anyopaque, Allocator) void,

    fn elems(self: *const Slot, comptime dt: DType) []dtype_mod.Scalar(dt) {
        // Slot bytes alias real Scalar(dt) storage, so the alignment holds.
        return @alignCast(std.mem.bytesAsSlice(dtype_mod.Scalar(dt), self.bytes));
    }

    fn elemsConst(self: *const Slot, comptime dt: DType) []const dtype_mod.Scalar(dt) {
        return self.elems(dt);
    }

    fn deinit(self: *Slot, allocator: Allocator) void {
        if (self.retained) |retained| self.release.?(retained, allocator);
        self.* = undefined;
    }
};

/// Logical elements per BlockTQ2_0 (the ggml QK_K super-block).
const ternary_block_len: usize = dtype_mod.qk_k_block_size;

/// One registered ternary genome. Blocks are BORROWED mutable storage; the
/// undo log (sized once at the per-member flip count) holds the active
/// member's (index, old code) pairs for reverse replay in `restore`.
const TernarySlot = struct {
    name: ?[]const u8, // borrowed
    blocks: []BlockTQ2_0, // mutable view aliasing the genome storage
    /// Logical element count (== blocks.len * 256).
    len: usize,
    undo: []UndoEntry,
    undo_len: usize = 0,
    /// Staged top-K entry count in the trainer's `ternary_entries` scratch
    /// (set by collectTernaryVotes, consumed by applyTernaryVotes within a
    /// single update call).
    pending: usize = 0,

    fn deinit(self: *TernarySlot, allocator: Allocator) void {
        allocator.free(self.undo);
        self.* = undefined;
    }
};

const UndoEntry = struct { index: usize, code: u8 };

/// A nonzero vote of the ternary update (see `Trainer.collectTernaryVotes`).
const VoteEntry = struct { index: usize, vote: f32 };

/// Ternary update application order: |vote| descending, index ascending —
/// a total order, so the applied top-K set is deterministic.
fn voteBefore(_: void, a: VoteEntry, b: VoteEntry) bool {
    if (@abs(a.vote) != @abs(b.vote)) return @abs(a.vote) > @abs(b.vote);
    return a.index < b.index;
}

/// Flip i of a ternary flip stream: index = at(seed, 2i) % len, delta bit =
/// at(seed, 2i+1) & 1 (1 = +1, 0 = -1), negated for the antithetic odd
/// member (`mirror`). Counter-based like the gaussian streams — any flip is
/// O(1)-addressable — and a checkpoint contract (see the module doc).
fn ternaryFlipAt(stream_seed: u64, i: u64, len: usize, mirror: bool) struct { index: usize, delta: i8 } {
    const index: usize = @intCast(rng.at(stream_seed, 2 * i) % @as(u64, len));
    const bit = rng.at(stream_seed, 2 * i + 1) & 1;
    const base: i8 = if (bit == 1) 1 else -1;
    return .{ .index = index, .delta = if (mirror) -base else base };
}

/// One clamped single-bin move on a stored code (w+1):
/// code' = clamp((code - 1) + delta, -1, +1) + 1.
fn moveCode(code: u8, delta: i8) u8 {
    const w = @as(i8, @intCast(code)) - 1;
    return @intCast(std.math.clamp(w + delta, -1, 1) + 1);
}

/// Crumb address of logical element e in tq2_0 layout: block e/256; within
/// the block, r = e % 256 splits into group g = r/128 (32-byte qs half),
/// lane l = (r%128)/32 (bit pair 2l+1:2l), byte (r%128)%32 — crumb lane l
/// of a group covers elements [g*128 + l*32, g*128 + (l+1)*32).
fn crumbAddr(e: usize) struct { block: usize, byte: usize, shift: u3 } {
    const r = e % ternary_block_len;
    const group = r / 128;
    const lane = (r % 128) / 32;
    const byte = (r % 128) % 32;
    return .{ .block = e / ternary_block_len, .byte = group * 32 + byte, .shift = @intCast(2 * lane) };
}

fn crumbGet(blocks: []const BlockTQ2_0, e: usize) u8 {
    const addr = crumbAddr(e);
    return (blocks[addr.block].qs[addr.byte] >> addr.shift) & 3;
}

fn crumbSet(blocks: []BlockTQ2_0, e: usize, code: u8) void {
    std.debug.assert(code <= 2);
    const addr = crumbAddr(e);
    const byte = &blocks[addr.block].qs[addr.byte];
    byte.* = (byte.* & ~(@as(u8, 3) << addr.shift)) | (code << addr.shift);
}

fn makeRelease(comptime Raw: type) *const fn (*anyopaque, Allocator) void {
    return struct {
        fn release(ptr: *anyopaque, allocator: Allocator) void {
            const v: *Raw = @ptrCast(@alignCast(ptr));
            v.deinit();
            allocator.destroy(v);
        }
    }.release;
}

fn validateFacadePtr(comptime P: type) type {
    const info = @typeInfo(P);
    if (info != .pointer or info.pointer.size != .one) {
        @compileError("es.Trainer.addParam expects a single-item pointer to a facade tensor");
    }
    const T = info.pointer.child;
    if (@typeInfo(T) != .@"struct" or !@hasDecl(T, "dtype") or !@hasField(T, "value")) {
        @compileError("es.Trainer.addParam expects a facade tensor, got " ++ @typeName(P));
    }
    if (T.dtype != .f32 and T.dtype != .f16 and T.dtype != .bf16) {
        @compileError("es.Trainer.addParam supports f32/f16/bf16 tensors only");
    }
    return T;
}

/// The GPU provider's ES dtype tag for a comptime DType (f16/f32 only —
/// bf16 has no device arm and stays on the CPU kernels).
fn esGpuDType(comptime dt: DType) ?backend_mod.gpu_impl.EsDType {
    return switch (dt) {
        .f16 => .f16,
        .f32 => .f32,
        else => null,
    };
}

/// One slot's view of a stream-cache region: `data` aliases the region
/// (global element index j maps to data[j]); `filled` says whether the
/// stream already holds this iteration's regenerated values.
const SlotCache = struct { data: []f32, filled: bool };

/// updateSlot's view of the cache: per-stream regions resolved to the
/// current slot inside the kernel (read-only trainer access).
const UpdateCacheView = struct {
    trainer: *const Trainer,
    slot_index: usize,
    regions: []const Trainer.CacheRegion,
};

/// data[j] += scaled * eps[j] over [0, data.len), chunk-parallel. `scaled`
/// already carries sign * sigma; per element the delta `scaled * eps[j]`
/// rounds once in f32, narrows to the parameter dtype (the reference's
/// `p.data.add_(sign*scale*noise)` semantics — the scalar multiply rounds to
/// p.dtype before the in-place add), and applies widen-add-narrow. The
/// +sigma and -sigma passes use the bitwise-same delta, so they cancel to
/// the usual `(x + t) - t` drift.
fn perturbSlot(
    comptime dt: DType,
    ctx: *ExecContext,
    data: []dtype_mod.Scalar(dt),
    stream_seed: u64,
    scaled: f32,
    cache: ?SlotCache,
) void {
    // Device arm: resident parameters perturb ON the GPU (bitwise-identical
    // kernels, no managed-page migration back to the CPU). The stream cache
    // is a CPU-path feature — when it is active the CPU path runs so the
    // cache fills truthfully.
    if (comptime backend_mod.gpu_impl.enabled) {
        if (comptime esGpuDType(dt)) |gpu_dt| {
            if (cache == null and backend_mod.gpu_impl.esPerturb(gpu_dt, std.mem.sliceAsBytes(data), stream_seed, scaled, data.len)) {
                return;
            }
        }
    }
    const Context = struct {
        data: []dtype_mod.Scalar(dt),
        stream_seed: u64,
        scaled: f32,
        cache: ?SlotCache,
    };
    parallelMap(ctx, data.len, perturb_min_len, Context{
        .data = data,
        .stream_seed = stream_seed,
        .scaled = scaled,
        .cache = cache,
    }, struct {
        fn runRange(c: Context, start: usize, end: usize) void {
            var scratch: [chunk_len]f32 = undefined;
            var j = start;
            while (j < end) {
                const len = @min(chunk_len, end - j);
                // The noise source: replay the cache, regenerate INTO the
                // cache (first use this iteration; chunk ranges are
                // disjoint), or regenerate into the stack scratch. Values
                // are identical on every path — caching is bitwise-neutral.
                const noise: []const f32 = if (c.cache) |slot_cache| blk: {
                    const region = slot_cache.data[j..][0..len];
                    if (!slot_cache.filled) rng.gaussianFillAtFast(c.stream_seed, j, region, 1.0);
                    break :blk region;
                } else blk: {
                    rng.gaussianFillAtFast(c.stream_seed, j, scratch[0..len], 1.0);
                    break :blk scratch[0..len];
                };
                for (c.data[j..][0..len], noise) |*p, eps| {
                    const t = dtype_mod.fromF32(dt, c.scaled * eps);
                    p.* = dtype_mod.fromF32(dt, dtype_mod.toF32(dt, p.*) + dtype_mod.toF32(dt, t));
                }
                j += len;
            }
        }
    }.runRange);
}

/// dst[j] = src[j] + sigma * eps[j] — the replica writer (serial; see
/// `materializeMember`). Same per-element math as `perturbSlot`.
fn materializeSlot(
    comptime dt: DType,
    src: []const dtype_mod.Scalar(dt),
    dst: []dtype_mod.Scalar(dt),
    stream_seed: u64,
    sigma: f32,
) void {
    var noise: [chunk_len]f32 = undefined;
    var j: usize = 0;
    while (j < src.len) {
        const len = @min(chunk_len, src.len - j);
        rng.gaussianFillAtFast(stream_seed, j, noise[0..len], 1.0);
        for (dst[j..][0..len], src[j..][0..len], noise[0..len]) |*d, s, eps| {
            const t = dtype_mod.fromF32(dt, sigma * eps);
            d.* = dtype_mod.fromF32(dt, dtype_mod.toF32(dt, s) + dtype_mod.toF32(dt, t));
        }
        j += len;
    }
}

/// data[j] += scale * sum_n coeffs[n] * eps_n[j], chunk-parallel with fp32
/// accumulation and the reference's rounding placement: `coeffs[n] * eps`
/// rounds, the accumulation adds round, the final `scale *` rounds once, the
/// delta narrows to the parameter dtype, and the add widens-adds-narrows.
/// Member order inside each element's accumulation is fixed (0..N), so the
/// result is bitwise independent of the chunking.
fn updateSlot(
    comptime dt: DType,
    ctx: *ExecContext,
    data: []dtype_mod.Scalar(dt),
    stream_seeds: []const u64,
    coeffs: []const f32,
    scale: f32,
    cache: ?UpdateCacheView,
) void {
    if (comptime backend_mod.gpu_impl.enabled) {
        if (comptime esGpuDType(dt)) |gpu_dt| {
            if (cache == null and backend_mod.gpu_impl.esUpdate(gpu_dt, std.mem.sliceAsBytes(data), stream_seeds, coeffs, scale, data.len)) {
                return;
            }
        }
    }
    const Context = struct {
        data: []dtype_mod.Scalar(dt),
        stream_seeds: []const u64,
        coeffs: []const f32,
        scale: f32,
        cache: ?UpdateCacheView,
    };
    parallelMap(ctx, data.len, update_min_len, Context{
        .data = data,
        .stream_seeds = stream_seeds,
        .coeffs = coeffs,
        .scale = scale,
        .cache = cache,
    }, struct {
        fn runRange(c: Context, start: usize, end: usize) void {
            var scratch: [chunk_len]f32 = undefined;
            var acc: [chunk_len]f32 = undefined;
            var j = start;
            while (j < end) {
                const len = @min(chunk_len, end - j);
                @memset(acc[0..len], 0);
                for (c.stream_seeds, c.coeffs, 0..) |stream_seed, coeff, stream| {
                    const noise: []const f32 = if (c.cache) |cache_view| blk: {
                        const view = cache_view.regions[stream];
                        const region = view.slotRegion(cache_view.trainer, cache_view.slot_index)[j..][0..len];
                        if (!view.filled) rng.gaussianFillAtFast(stream_seed, j, region, 1.0);
                        break :blk region;
                    } else blk: {
                        rng.gaussianFillAtFast(stream_seed, j, scratch[0..len], 1.0);
                        break :blk scratch[0..len];
                    };
                    for (acc[0..len], noise) |*a, eps| {
                        a.* += coeff * eps;
                    }
                }
                for (c.data[j..][0..len], acc[0..len]) |*p, a| {
                    const delta = dtype_mod.fromF32(dt, c.scale * a);
                    p.* = dtype_mod.fromF32(dt, dtype_mod.toF32(dt, p.*) + dtype_mod.toF32(dt, delta));
                }
                j += len;
            }
        }
    }.runRange);
}

/// The AWD proximal step on one slot, with the reference's exact in-place
/// op chain (each step computes in f32 and rounds to the parameter dtype,
/// mirroring torch's per-op `sub_`/`mul_`/`add_` semantics so parity is
/// bitwise for every dtype): d = round(theta - theta_0); l2 rounds
/// d * (1 - decay_step), l1 rounds |d| - decay_step, clamps at 0 and
/// restores the sign (torch sign(0) = 0 collapses to the same result);
/// finally theta = round(d' + theta_0). Chunk-parallel and
/// element-independent like the other kernels.
fn anchorSlot(
    comptime dt: DType,
    ctx: *ExecContext,
    data: []dtype_mod.Scalar(dt),
    anchor: []const dtype_mod.Scalar(dt),
    decay_step: f32,
    decay: AnchorDecay,
) void {
    if (comptime backend_mod.gpu_impl.enabled) {
        if (comptime esGpuDType(dt)) |gpu_dt| {
            if (backend_mod.gpu_impl.esAnchor(gpu_dt, std.mem.sliceAsBytes(data), std.mem.sliceAsBytes(anchor), decay_step, decay == .l1, data.len)) {
                return;
            }
        }
    }
    const Context = struct {
        data: []dtype_mod.Scalar(dt),
        anchor: []const dtype_mod.Scalar(dt),
        decay_step: f32,
        decay: AnchorDecay,
    };
    parallelMap(ctx, data.len, perturb_min_len, Context{
        .data = data,
        .anchor = anchor,
        .decay_step = decay_step,
        .decay = decay,
    }, struct {
        fn runRange(c: Context, start: usize, end: usize) void {
            switch (c.decay) {
                .l2 => {
                    const keep = 1 - c.decay_step;
                    for (c.data[start..end], c.anchor[start..end]) |*p, a| {
                        const anchor_wide = dtype_mod.toF32(dt, a);
                        const d = dtype_mod.fromF32(dt, dtype_mod.toF32(dt, p.*) - anchor_wide);
                        const kept = dtype_mod.fromF32(dt, dtype_mod.toF32(dt, d) * keep);
                        p.* = dtype_mod.fromF32(dt, dtype_mod.toF32(dt, kept) + anchor_wide);
                    }
                },
                .l1 => {
                    for (c.data[start..end], c.anchor[start..end]) |*p, a| {
                        const anchor_wide = dtype_mod.toF32(dt, a);
                        const d = dtype_mod.fromF32(dt, dtype_mod.toF32(dt, p.*) - anchor_wide);
                        const d_wide = dtype_mod.toF32(dt, d);
                        const thresholded = dtype_mod.fromF32(dt, @abs(d_wide) - c.decay_step);
                        const clamped = @max(dtype_mod.toF32(dt, thresholded), 0);
                        const shrunk: f32 = if (d_wide < 0) -clamped else clamped;
                        p.* = dtype_mod.fromF32(dt, shrunk + anchor_wide);
                    }
                },
                .none => unreachable,
            }
        }
    }.runRange);
}

/// optim.zig's element-independent parallel map, with a caller-chosen
/// threshold (noise kernels are costlier per element than optimizer steps).
/// Bitwise identical to the serial path for any thread count.
fn parallelMap(
    ctx: *ExecContext,
    n: usize,
    min_len: usize,
    context: anytype,
    comptime runRange: fn (@TypeOf(context), usize, usize) void,
) void {
    if (n >= min_len) {
        if (ctx.workPool()) |pool| {
            const Ctx = @TypeOf(context);
            const Task = struct {
                context: Ctx,
                start: usize,
                end: usize,
                fn run(task: *const @This()) void {
                    runRange(task.context, task.start, task.end);
                }
            };
            const task_count = @min(
                parallel.cpuThreadCount(parallel.vector_max_threads),
                1 + n / min_len,
            );
            if (task_count > 1) {
                var tasks: [parallel.vector_max_threads]Task = undefined;
                for (0..task_count) |i| {
                    tasks[i] = .{ .context = context, .start = i * n / task_count, .end = (i + 1) * n / task_count };
                }
                pool.parallelChunks(Task, tasks[0..task_count], Task.run);
                return;
            }
        }
    }
    runRange(context, 0, n);
}

test {
    _ = @import("es_tests.zig");
}
