//! Behavioral + parity tests for the ES module (`es.zig`): numpy-reference
//! goldens (generated by tools/gen_es_goldens.py — regenerate there, paste
//! here), noise-scheme semantics, restore modes, replica materialization,
//! chunk-parallel determinism, the step/evaluateMembers drivers, registry
//! integration, tripwires, and end-to-end convergence on a sphere objective.
//!
//! Golden tolerances: es.zig draws noise through `rng.gaussianFillAtFast`
//! (f32 polynomial transcendentals) while the numpy generator uses f64 libm
//! — same uniforms, values a few f32 ulps apart — so numpy goldens compare
//! with per-dtype tolerances instead of bitwise (same policy as the torch
//! optimizer goldens; sigma scaling shrinks the noise deltas well below
//! every tolerance). Bitwise guarantees are covered separately by the
//! test-local serial reference (same kernel at runtime) and the
//! twin-trainer tests.

const std = @import("std");
const ag = @import("ag.zig");
const dtype_mod = @import("dtype.zig");
const es = @import("es.zig");
const exec_mod = @import("exec.zig");
const param_registry_mod = @import("param_registry.zig");
const rng = @import("rng.zig");

const ExecContext = exec_mod.ExecContext;
const ParamRegistry = param_registry_mod.ParamRegistry;
const Tensor = ag.Tensor;

const F16Tensor = Tensor(.{ .dtype = .f16, .tags = .{.n} });
const Bf16Tensor = Tensor(.{ .dtype = .bf16, .tags = .{.n} });

fn expectCloseSlices(expected: []const f32, actual: []const f32, tolerance: f32) !void {
    try std.testing.expectEqual(expected.len, actual.len);
    for (expected, actual) |e, a| {
        try std.testing.expectApproxEqAbs(e, a, tolerance);
    }
}

fn widenF16(dst: []f32, src: []const f16) void {
    for (dst, src) |*d, s| d.* = @floatCast(s);
}

fn widenBf16(dst: []f32, src: []const u16) void {
    for (dst, src) |*d, s| d.* = dtype_mod.bf16ToF32(s);
}

// The golden scenario's parameters (tools/gen_es_goldens.py).
const theta_a = [_]f32{ 0.8, -1.25, 0.5, 2.0, -0.125, 1.5, -0.75 };
const theta_b = [_]f16{ 0.5, -0.25, 1.0, -1.5, 2.0, 0.125, -0.875, 0.0625 };
const theta_c_f32 = [_]f32{ 1.0, -2.0, 0.5, -0.25, 3.0 };
const theta_d = [_]f32{ -0.5, 0.75, -1.0, 0.25, 1.125, -2.5, 0.375 };

/// The four golden slots as facade tensors (a/d f32, b f16, c bf16 — a and d
/// share a length so the correlated scheme is observable). `b` is a VARIABLE
/// to cover the autograd-facade registration path; ES treats it identically.
const GoldenParams = struct {
    a: Tensor(.{.n}),
    b: F16Tensor,
    c: Bf16Tensor,
    d: Tensor(.{.n}),

    fn init(ctx: *ExecContext) !GoldenParams {
        var theta_c_bits: [theta_c_f32.len]u16 = undefined;
        for (&theta_c_bits, theta_c_f32) |*bits, v| bits.* = dtype_mod.f32ToBf16(v);

        var a = try Tensor(.{.n}).fromSlice(ctx, .{theta_a.len}, &theta_a);
        errdefer a.deinit();
        var b = try F16Tensor.fromSlice(ctx, .{theta_b.len}, &theta_b);
        errdefer b.deinit();
        var c = try Bf16Tensor.fromSlice(ctx, .{theta_c_f32.len}, &theta_c_bits);
        errdefer c.deinit();
        const d = try Tensor(.{.n}).variableFromSlice(ctx, .{theta_d.len}, &theta_d);
        return .{ .a = a, .b = b, .c = c, .d = d };
    }

    fn deinit(self: *GoldenParams) void {
        self.d.deinit();
        self.c.deinit();
        self.b.deinit();
        self.a.deinit();
        self.* = undefined;
    }

    fn register(self: *GoldenParams, trainer: *es.Trainer) !void {
        try trainer.addParamNamed(&self.a, "a");
        try trainer.addParamNamed(&self.b, "b");
        try trainer.addParamNamed(&self.c, "c");
        try trainer.addParamNamed(&self.d, "d");
    }

    /// Widened views of the four slots for tolerance comparison.
    fn expectClose(self: *const GoldenParams, ea: []const f32, eb: []const f32, ec: []const f32, ed: []const f32) !void {
        var wide_b: [theta_b.len]f32 = undefined;
        widenF16(&wide_b, try self.b.dataConst());
        var wide_c: [theta_c_f32.len]f32 = undefined;
        widenBf16(&wide_c, try self.c.dataConst());
        // f32 slots: tight (libm ulp headroom only). f16/bf16: half an ulp at
        // the slot's magnitude — a flipped rounding from a 1-ulp noise
        // difference stays within, a missing/misplaced update does not.
        try expectCloseSlices(ea, try self.a.dataConst(), 1e-6);
        try expectCloseSlices(eb, &wide_b, 1e-3);
        try expectCloseSlices(ec, &wide_c, 1.6e-2);
        try expectCloseSlices(ed, try self.d.dataConst(), 1e-6);
    }
};

// Generated by tools/gen_es_goldens.py — scenario A: sigma=0.05,
// alpha=null (sigma/2), population=4, iid, z_score, seed=42; scenario B:
// sigma=0.02, alpha=0.01, population=3, correlated, none, seed=42.
const golden_perturbed_m2_a = [_]f32{ 0.77865386, -1.1763682, 0.5002475, 2.0686219, -0.23082645, 1.5209504, -0.79979795 };
const golden_perturbed_m2_b = [_]f32{ 0.6044922, -0.2626953, 1.0126953, -1.4921875, 2.0058594, 0.21887207, -0.8979492, 0.03668213 };
const golden_perturbed_m2_c = [_]f32{ 1.03125, -1.9453125, 0.515625, -0.26171875, 2.96875 };
const golden_perturbed_m2_d = [_]f32{ -0.4979383, 0.81982946, -0.9709101, 0.2605065, 1.1253201, -2.4784007, 0.42369875 };

const golden_a_after2_a = [_]f32{ 0.78395367, -1.2750047, 0.51845896, 1.9830192, -0.123018675, 1.4779749, -0.7360478 };
const golden_a_after2_b = [_]f32{ 0.5024414, -0.25390625, 0.9951172, -1.4755859, 2.0, 0.13098145, -0.84472656, 0.057617188 };
const golden_a_after2_c = [_]f32{ 0.99609375, -2.0, 0.50390625, -0.23535156, 2.984375 };
const golden_a_after2_d = [_]f32{ -0.48093694, 0.7390066, -1.0273292, 0.24397261, 1.1278526, -2.4969428, 0.38026085 };

const golden_b_after1_a = [_]f32{ 0.805725, -1.2552462, 0.50182354, 1.9955155, -0.12337347, 1.4921284, -0.7420049 };
const golden_b_after1_b = [_]f32{ 0.5058594, -0.25512695, 1.0019531, -1.5048828, 2.0019531, 0.117126465, -0.8671875, 0.058746338 };
const golden_b_after1_c = [_]f32{ 1.0078125, -2.0, 0.5, -0.25390625, 3.0 };
const golden_b_after1_d = [_]f32{ -0.49427503, 0.7447538, -0.99817646, 0.24551547, 1.1266265, -2.5078716, 0.38299516 };

// Scenario C: sigma=0.05, alpha=null (sigma/2), population=4, iid,
// centered_ranks, seed=42 (coefficients cross-checked by the generator
// against the verbatim OpenAI evolution-strategies-starter code).
const golden_c_after1_a = [_]f32{ 0.7999262, -1.2567196, 0.5009102, 1.9904276, -0.121586315, 1.498365, -0.74659526 };
const golden_c_after1_b = [_]f32{ 0.50097656, -0.25195312, 1.0039062, -1.4990234, 1.9960938, 0.12561035, -0.8745117, 0.06329346 };
const golden_c_after1_c = [_]f32{ 1.0, -1.9921875, 0.5, -0.25, 3.0 };
const golden_c_after1_d = [_]f32{ -0.49406612, 0.746654, -1.002035, 0.25510928, 1.1217488, -2.5011604, 0.3746752 };

const config_a = es.Config{ .sigma = 0.05, .population = 4, .noise = .iid, .reward_norm = .z_score, .seed = 42 };
const config_b = es.Config{ .sigma = 0.02, .alpha = 0.01, .population = 3, .noise = .correlated, .reward_norm = .none, .seed = 42 };
const rewards_iter0 = [_]f32{ 0.1, 0.9, -0.4, 0.35 };
const rewards_iter1 = [_]f32{ 1.0, -1.0, 0.25, 0.5 };
const rewards_b = [_]f32{ 0.5, -0.25, 1.5 };

test "es config validation" {
    const allocator = std.testing.allocator;
    try std.testing.expectError(es.EsError.InvalidConfig, es.Trainer.init(allocator, .{ .sigma = 0 }));
    try std.testing.expectError(es.EsError.InvalidConfig, es.Trainer.init(allocator, .{ .sigma = -0.1 }));
    try std.testing.expectError(es.EsError.InvalidConfig, es.Trainer.init(allocator, .{ .alpha = 0 }));
    try std.testing.expectError(es.EsError.InvalidConfig, es.Trainer.init(allocator, .{ .population = 1 }));
    var trainer = try es.Trainer.init(allocator, .{});
    defer trainer.deinit();
    try std.testing.expectEqual(@as(f32, 0.0005), trainer.alphaValue()); // sigma/2 default
}

test "es golden: perturb matches the numpy reference, restore bounds the drift" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    var params = try GoldenParams.init(&ctx);
    defer params.deinit();
    var trainer = try es.Trainer.init(allocator, config_a);
    defer trainer.deinit();
    try params.register(&trainer);
    try std.testing.expectEqual(@as(usize, 4), trainer.paramCount());
    try std.testing.expectEqual(theta_a.len + theta_b.len + theta_c_f32.len + theta_d.len, trainer.elementCount());

    try trainer.perturb(&ctx, 2);
    try params.expectClose(&golden_perturbed_m2_a, &golden_perturbed_m2_b, &golden_perturbed_m2_c, &golden_perturbed_m2_d);

    // Regenerate-restore drift: bounded by one rounding of the perturbed
    // value per element ((x + t) - t), i.e. ~an ulp at the slot's magnitude.
    try trainer.restore(&ctx, 2);
    var wide_b: [theta_b.len]f32 = undefined;
    widenF16(&wide_b, try params.b.dataConst());
    var wide_c: [theta_c_f32.len]f32 = undefined;
    widenBf16(&wide_c, try params.c.dataConst());
    var theta_b_f32: [theta_b.len]f32 = undefined;
    widenF16(&theta_b_f32, &theta_b);
    try expectCloseSlices(&theta_a, try params.a.dataConst(), 1e-6);
    try expectCloseSlices(&theta_b_f32, &wide_b, 2e-3);
    try expectCloseSlices(&theta_c_f32, &wide_c, 3.2e-2);
    try expectCloseSlices(&theta_d, try params.d.dataConst(), 1e-6);
}

test "es golden: two z-score updates match the numpy reference (scenario A)" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    var params = try GoldenParams.init(&ctx);
    defer params.deinit();
    var trainer = try es.Trainer.init(allocator, config_a);
    defer trainer.deinit();
    try params.register(&trainer);

    const stats0 = try trainer.update(&ctx, &rewards_iter0);
    // f32 reward literals are inexact, so the f64 mean is only ~1e-8 close.
    try std.testing.expectApproxEqAbs(@as(f64, 0.2375), stats0.mean_reward, 1e-7);
    try std.testing.expectEqual(@as(f32, -0.4), stats0.min_reward);
    try std.testing.expectEqual(@as(f32, 0.9), stats0.max_reward);
    try std.testing.expectEqual(@as(u64, 1), trainer.iteration);
    _ = try trainer.update(&ctx, &rewards_iter1);
    try std.testing.expectEqual(@as(u64, 2), trainer.iteration);

    try params.expectClose(&golden_a_after2_a, &golden_a_after2_b, &golden_a_after2_c, &golden_a_after2_d);
}

test "es golden: correlated noise + raw rewards match the numpy reference (scenario B)" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    var params = try GoldenParams.init(&ctx);
    defer params.deinit();
    var trainer = try es.Trainer.init(allocator, config_b);
    defer trainer.deinit();
    try params.register(&trainer);

    _ = try trainer.update(&ctx, &rewards_b);
    try params.expectClose(&golden_b_after1_a, &golden_b_after1_b, &golden_b_after1_c, &golden_b_after1_d);
}

test "es golden: centered-rank shaping matches the numpy/OpenAI reference (scenario C)" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    var params = try GoldenParams.init(&ctx);
    defer params.deinit();
    var config = config_a;
    config.reward_norm = .centered_ranks;
    var trainer = try es.Trainer.init(allocator, config);
    defer trainer.deinit();
    try params.register(&trainer);

    _ = try trainer.update(&ctx, &rewards_iter0);
    try params.expectClose(&golden_c_after1_a, &golden_c_after1_b, &golden_c_after1_c, &golden_c_after1_d);
}

test "es centered ranks: outlier clamped, ties pinned by member index, all-equal steps anyway" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    // Zero parameters expose the applied coefficients directly:
    // theta' = scale * sum_n C_n * eps_n with theta = 0 and one member's
    // noise recovered via materializeMember... simpler: verify through the
    // update's EFFECT — an outlier reward must not dominate. Two trainers,
    // same seed: one gets a catastrophic outlier reward, one a mild one; the
    // rank-shaped updates must be IDENTICAL (ranks see only the ordering).
    inline for (0..2) |variant| {
        const zeros = [_]f32{0} ** 64;
        var w = try Tensor(.{.n}).fromSlice(&ctx, .{zeros.len}, &zeros);
        defer w.deinit();
        var trainer = try es.Trainer.init(allocator, .{
            .sigma = 0.1,
            .alpha = 0.05,
            .population = 4,
            .reward_norm = .centered_ranks,
            .seed = 77,
        });
        defer trainer.deinit();
        try trainer.addParam(&w);
        // Same ordering, wildly different magnitudes (variant 1 has the
        // CE-14-style catastrophic member).
        const rewards: [4]f32 = if (variant == 0) .{ -4.0, -4.5, -3.9, -5.0 } else .{ -4.0, -4.5, -3.9, -1.0e6 };
        _ = try trainer.update(&ctx, &rewards);
        if (variant == 0) {
            // Stash the reference update for the comparison below.
            @memcpy(rank_update_scratch[0..zeros.len], try w.dataConst());
        } else {
            try std.testing.expectEqualSlices(f32, rank_update_scratch[0..zeros.len], try w.dataConst());
        }
    }

    // All-equal rewards: unlike z_score's exact zero update, ranks still
    // spread members over [-0.5, 0.5] (tie order = member index) and take a
    // mean-zero phantom step — documented behavior, pinned here.
    {
        const zeros = [_]f32{0} ** 8;
        var w = try Tensor(.{.n}).fromSlice(&ctx, .{zeros.len}, &zeros);
        defer w.deinit();
        var trainer = try es.Trainer.init(allocator, .{
            .sigma = 0.1,
            .alpha = 0.05,
            .population = 3,
            .reward_norm = .centered_ranks,
            .seed = 78,
        });
        defer trainer.deinit();
        try trainer.addParam(&w);
        _ = try trainer.update(&ctx, &.{ 0.7, 0.7, 0.7 });
        var moved = false;
        for (try w.dataConst()) |x| moved = moved or (x != 0);
        try std.testing.expect(moved);
    }
}

var rank_update_scratch: [64]f32 = undefined;

test "es antithetic: mirrored pairs, folded update matches a signed serial reference" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    // Mirror structure: on zero parameters (fl(0 + t) = t exactly) member
    // 2k+1's perturbation is the exact negation of member 2k's.
    {
        const zeros = [_]f32{0} ** 32;
        var w = try Tensor(.{.n}).fromSlice(&ctx, .{zeros.len}, &zeros);
        defer w.deinit();
        var trainer = try es.Trainer.init(allocator, .{ .sigma = 0.1, .population = 4, .antithetic = true, .seed = 31 });
        defer trainer.deinit();
        try trainer.addParam(&w);

        var plus: [zeros.len]f32 = undefined;
        try trainer.perturb(&ctx, 0);
        @memcpy(&plus, try w.dataConst());
        try trainer.restore(&ctx, 0);
        try trainer.perturb(&ctx, 1);
        for (plus, try w.dataConst()) |p, m| try std.testing.expectEqual(-p, m);
        try trainer.restore(&ctx, 1);

        // materializeMember carries the same signs.
        const replica = try allocator.alloc(f32, zeros.len);
        defer allocator.free(replica);
        try trainer.materializeMember(1, &.{std.mem.sliceAsBytes(replica)});
        for (plus, replica) |p, m| try std.testing.expectEqual(-p, m);
    }

    // Folded update == signed straight-line serial reference (bitwise):
    // per pair k the contribution is (C_2k - C_2k+1) * eps_k, division by
    // the FULL population.
    {
        const n = 10_000;
        const population = 6;
        const theta0 = try allocator.alloc(f32, n);
        defer allocator.free(theta0);
        rng.uniformFill(3, theta0, -1.0, 1.0);
        var w = try Tensor(.{.n}).fromSlice(&ctx, .{n}, theta0);
        defer w.deinit();
        var trainer = try es.Trainer.init(allocator, .{
            .sigma = 0.05,
            .alpha = 0.02,
            .population = population,
            .antithetic = true,
            .noise = .correlated, // public memberSeed = the stream seed
            .reward_norm = .z_score,
            .seed = 13,
        });
        defer trainer.deinit();
        try trainer.addParam(&w);

        const rewards = [_]f32{ 0.5, -0.25, 1.5, 1.0, -2.0, 0.0 };
        var mean: f64 = 0;
        for (rewards) |r| mean += r;
        mean /= rewards.len;
        var variance: f64 = 0;
        for (rewards) |r| variance += (r - mean) * (r - mean);
        variance /= rewards.len;
        const std_reward = @sqrt(variance);
        var coeffs: [population]f32 = undefined;
        for (&coeffs, rewards) |*c, r| c.* = @floatCast((r - mean) / (std_reward + 1e-8));

        const expected = try allocator.dupe(f32, theta0);
        defer allocator.free(expected);
        const noise = try allocator.alloc(f32, n);
        defer allocator.free(noise);
        const acc = try allocator.alloc(f32, n);
        defer allocator.free(acc);
        @memset(acc, 0);
        for (0..population / 2) |pair| {
            rng.gaussianFillAtFast(trainer.memberSeed(2 * pair), 0, noise, 1.0);
            const folded = coeffs[2 * pair] - coeffs[2 * pair + 1];
            for (acc, noise) |*a, eps| a.* += folded * eps;
        }
        const scale = trainer.alphaValue() / @as(f32, population);
        for (expected, acc) |*p, a| p.* += scale * a;

        _ = try trainer.update(&ctx, &rewards);
        try std.testing.expectEqualSlices(f32, expected, try w.dataConst());
    }

    // Odd population + antithetic is a config error.
    try std.testing.expectError(es.EsError.InvalidConfig, es.Trainer.init(allocator, .{ .population = 3, .antithetic = true }));
}

test "es antithetic converges on the sphere objective" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    const n = 16;
    var w = try Tensor(.{.n}).fromSlice(&ctx, .{n}, &([_]f32{1.0} ** n));
    defer w.deinit();
    var trainer = try es.Trainer.init(allocator, .{ .sigma = 0.1, .alpha = 0.05, .population = 16, .antithetic = true, .seed = 1234 });
    defer trainer.deinit();
    try trainer.addParam(&w);

    const Evaluator = struct {
        w: *const Tensor(.{.n}),

        fn sqNorm(self: *const @This()) !f64 {
            var total: f64 = 0;
            for (try self.w.dataConst()) |x| total += @as(f64, x) * @as(f64, x);
            return total;
        }

        pub fn eval(self: *const @This(), member: usize) !f32 {
            _ = member;
            return @floatCast(-(try self.sqNorm()));
        }
    };
    const evaluator = Evaluator{ .w = &w };
    const initial = 16.0;
    for (0..150) |_| _ = try trainer.step(&ctx, &evaluator);
    var final: f64 = 0;
    for (try w.dataConst()) |x| final += @as(f64, x) * @as(f64, x);
    try std.testing.expect(final < initial * 0.25);
}

test "es stream cache: cached and uncached runs are bitwise identical" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    inline for (.{ false, true }) |antithetic| {
        const configs = [2]es.Config{
            .{ .sigma = 0.05, .population = 4, .antithetic = antithetic, .restore_mode = .snapshot, .seed = 55 },
            .{ .sigma = 0.05, .population = 4, .antithetic = antithetic, .restore_mode = .snapshot, .seed = 55, .cache_streams = true },
        };
        var thetas: [2][2][]f32 = undefined; // [trainer][slot]
        inline for (0..2) |which| {
            var a = try Tensor(.{.n}).fromSlice(&ctx, .{theta_a.len}, &theta_a);
            defer a.deinit();
            var d = try Tensor(.{.n}).fromSlice(&ctx, .{theta_d.len}, &theta_d);
            defer d.deinit();
            var trainer = try es.Trainer.init(allocator, configs[which]);
            defer trainer.deinit();
            try trainer.addParam(&a);
            try trainer.addParam(&d);

            // Two full iterations: perturb/eval/restore every member (the
            // eval fills the cache), then update; second iteration reuses
            // the machinery post-invalidation.
            inline for (.{ [_]f32{ 0.1, 0.9, -0.4, 0.35 }, [_]f32{ 1.0, -1.0, 0.25, 0.5 } }) |rewards| {
                for (0..4) |member| {
                    try trainer.perturb(&ctx, member);
                    try trainer.restore(&ctx, member);
                }
                _ = try trainer.update(&ctx, &rewards);
            }
            thetas[which][0] = try allocator.dupe(f32, try a.dataConst());
            thetas[which][1] = try allocator.dupe(f32, try d.dataConst());
        }
        defer for (thetas) |pair| for (pair) |t| allocator.free(t);
        try std.testing.expectEqualSlices(f32, thetas[0][0], thetas[1][0]);
        try std.testing.expectEqualSlices(f32, thetas[0][1], thetas[1][1]);
    }
}

test "es anchored weight decay: l2 proximal pull matches the formula bitwise, l1 thresholds to the anchor" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    const theta0 = [_]f32{ 0.8, -1.25, 0.5, 2.0, -0.125, 1.5, -0.75, 0.0625 };
    const rewards = [_]f32{ 0.1, 0.9, -0.4, 0.35 };

    // Plain ES twin: theta_es after one update, no decay.
    var w_es = try Tensor(.{.n}).fromSlice(&ctx, .{theta0.len}, &theta0);
    defer w_es.deinit();
    var plain = try es.Trainer.init(allocator, .{ .sigma = 0.05, .alpha = 0.02, .population = 4, .seed = 42 });
    defer plain.deinit();
    try plain.addParam(&w_es);
    _ = try plain.update(&ctx, &rewards);

    // AWD twin: identical config + l2 anchor decay from theta0.
    var w_awd = try Tensor(.{.n}).fromSlice(&ctx, .{theta0.len}, &theta0);
    defer w_awd.deinit();
    var anchored = try es.Trainer.init(allocator, .{
        .sigma = 0.05,
        .alpha = 0.02,
        .population = 4,
        .seed = 42,
        .anchor_decay = .l2,
        .anchor_lambda = 10,
    });
    defer anchored.deinit();
    try anchored.addParam(&w_awd);
    try anchored.captureAnchor();
    _ = try anchored.update(&ctx, &rewards);

    // theta_awd == theta_0 + (1 - alpha*lambda) * (theta_es - theta_0),
    // replicated with the kernel's exact f32 op order (single narrowing).
    const keep: f32 = 1 - 0.02 * 10.0;
    for (try w_es.dataConst(), try w_awd.dataConst(), theta0) |es_v, awd_v, a| {
        const expected = a + (es_v - a) * keep;
        try std.testing.expectEqual(expected, awd_v);
    }

    // l1 with a huge threshold collapses the whole update: theta returns to
    // the anchor bitwise (softshrink zeroes every |d| < alpha*lambda).
    var w_l1 = try Tensor(.{.n}).fromSlice(&ctx, .{theta0.len}, &theta0);
    defer w_l1.deinit();
    var strong = try es.Trainer.init(allocator, .{
        .sigma = 0.05,
        .alpha = 0.02,
        .population = 4,
        .seed = 42,
        .anchor_decay = .l1,
        .anchor_lambda = 1e6,
    });
    defer strong.deinit();
    try strong.addParam(&w_l1);
    try strong.captureAnchor();
    _ = try strong.update(&ctx, &rewards);
    try std.testing.expectEqualSlices(f32, &theta0, try w_l1.dataConst());

    // Validation and the missing-anchor tripwire.
    try std.testing.expectError(es.EsError.InvalidConfig, es.Trainer.init(allocator, .{ .anchor_decay = .l2 })); // lambda 0
    try std.testing.expectError(es.EsError.InvalidConfig, es.Trainer.init(allocator, .{
        .alpha = 0.5,
        .anchor_decay = .l2,
        .anchor_lambda = 2, // alpha*lambda = 1: the l2 shrink degenerates
    }));
    var w_missing = try Tensor(.{.n}).fromSlice(&ctx, .{4}, &.{ 1, 2, 3, 4 });
    defer w_missing.deinit();
    var no_anchor = try es.Trainer.init(allocator, .{ .population = 4, .anchor_decay = .l2, .anchor_lambda = 1 });
    defer no_anchor.deinit();
    try no_anchor.addParam(&w_missing);
    try std.testing.expectError(es.EsError.AnchorMissing, no_anchor.update(&ctx, &.{ 0.0, 1.0, 2.0, 3.0 }));
}

test "es noise schemes: correlated shares same-length streams, iid does not" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    inline for (.{ es.NoiseScheme.correlated, es.NoiseScheme.iid }) |scheme| {
        // Zero parameters expose the raw noise: fl(0 + t) = t exactly.
        const zeros = [_]f32{0} ** 6;
        var u = try Tensor(.{.n}).fromSlice(&ctx, .{zeros.len}, &zeros);
        defer u.deinit();
        var v = try Tensor(.{.n}).fromSlice(&ctx, .{zeros.len}, &zeros);
        defer v.deinit();
        var trainer = try es.Trainer.init(allocator, .{ .sigma = 0.02, .alpha = 0.01, .population = 3, .noise = scheme, .seed = 42 });
        defer trainer.deinit();
        try trainer.addParam(&u);
        try trainer.addParam(&v);
        try trainer.perturb(&ctx, 0);
        const equal = std.mem.eql(f32, try u.dataConst(), try v.dataConst());
        try std.testing.expectEqual(scheme == .correlated, equal);
        for (try u.dataConst()) |x| try std.testing.expect(x != 0); // noise actually landed
    }
}

test "es snapshot restore is bitwise exact" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    var params = try GoldenParams.init(&ctx);
    defer params.deinit();
    var config = config_a;
    config.restore_mode = .snapshot;
    var trainer = try es.Trainer.init(allocator, config);
    defer trainer.deinit();
    try params.register(&trainer);

    var before_a: [theta_a.len]u32 = undefined;
    for (&before_a, try params.a.dataConst()) |*bits, v| bits.* = @bitCast(v);
    var before_b: [theta_b.len]u16 = undefined;
    for (&before_b, try params.b.dataConst()) |*bits, v| bits.* = @bitCast(v);

    for (0..config.population) |member| {
        try trainer.perturb(&ctx, member);
        try trainer.restore(&ctx, member);
    }
    for (before_a, try params.a.dataConst()) |bits, v| try std.testing.expectEqual(bits, @as(u32, @bitCast(v)));
    for (before_b, try params.b.dataConst()) |bits, v| try std.testing.expectEqual(bits, @as(u16, @bitCast(v)));
}

test "es materializeMember matches in-place perturbation bitwise" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    var params = try GoldenParams.init(&ctx);
    defer params.deinit();
    var trainer = try es.Trainer.init(allocator, config_a);
    defer trainer.deinit();
    try params.register(&trainer);

    // Replicas allocated as typed slices (element alignment guaranteed).
    const rep_a = try allocator.alloc(f32, theta_a.len);
    defer allocator.free(rep_a);
    const rep_b = try allocator.alloc(f16, theta_b.len);
    defer allocator.free(rep_b);
    const rep_c = try allocator.alloc(u16, theta_c_f32.len);
    defer allocator.free(rep_c);
    const rep_d = try allocator.alloc(f32, theta_d.len);
    defer allocator.free(rep_d);
    const dst = [_][]u8{
        std.mem.sliceAsBytes(rep_a),
        std.mem.sliceAsBytes(rep_b),
        std.mem.sliceAsBytes(rep_c),
        std.mem.sliceAsBytes(rep_d),
    };
    try trainer.materializeMember(1, &dst);

    try trainer.perturb(&ctx, 1);
    try std.testing.expectEqualSlices(f32, try params.a.dataConst(), rep_a);
    try std.testing.expectEqualSlices(f16, try params.b.dataConst(), rep_b);
    try std.testing.expectEqualSlices(u16, try params.c.dataConst(), rep_c);
    try std.testing.expectEqualSlices(f32, try params.d.dataConst(), rep_d);
    try trainer.restore(&ctx, 1);
}

test "es update matches a straight-line serial reference bitwise (chunk-parallel path)" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    // Large enough to fan out over the worker team (update_min_len = 2^11).
    const n = 40_000;
    const population = 5;
    const theta0 = try allocator.alloc(f32, n);
    defer allocator.free(theta0);
    rng.uniformFill(7, theta0, -2.0, 2.0);

    var w = try Tensor(.{.n}).fromSlice(&ctx, .{n}, theta0);
    defer w.deinit();
    // .correlated so the noise stream seed is the PUBLIC memberSeed (the
    // reference below needs it without touching module internals).
    var trainer = try es.Trainer.init(allocator, .{ .sigma = 0.01, .alpha = 0.004, .population = population, .noise = .correlated, .reward_norm = .z_score, .seed = 99 });
    defer trainer.deinit();
    try trainer.addParam(&w);

    // Independent serial reference: z-score coefficients (f64 stats, ddof=0,
    // +1e-8 on the std), fp32 mul-then-add accumulation in member order,
    // one final alpha/population scaling, plain f32 add.
    const rewards = [_]f32{ 0.3, -1.2, 0.75, 0.0, 2.5 };
    var mean: f64 = 0;
    for (rewards) |r| mean += r;
    mean /= rewards.len;
    var variance: f64 = 0;
    for (rewards) |r| variance += (r - mean) * (r - mean);
    variance /= rewards.len;
    const std_reward = @sqrt(variance);
    var coeffs: [population]f32 = undefined;
    for (&coeffs, rewards) |*c, r| c.* = @floatCast((r - mean) / (std_reward + 1e-8));

    const expected = try allocator.alloc(f32, n);
    defer allocator.free(expected);
    @memcpy(expected, theta0);
    const noise = try allocator.alloc(f32, n);
    defer allocator.free(noise);
    const acc = try allocator.alloc(f32, n);
    defer allocator.free(acc);
    @memset(acc, 0);
    for (0..population) |member| {
        rng.gaussianFillAtFast(trainer.memberSeed(member), 0, noise, 1.0);
        for (acc, noise) |*a, eps| a.* += coeffs[member] * eps;
    }
    const scale = trainer.alphaValue() / @as(f32, population);
    for (expected, acc) |*p, a| p.* += scale * a;

    _ = try trainer.update(&ctx, &rewards);
    try std.testing.expectEqualSlices(f32, expected, try w.dataConst());
}

test "es step equals manual update on a twin (snapshot restore), advances iteration" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    var config = config_a;
    config.restore_mode = .snapshot; // bitwise restore => twin comparison is exact

    var params = try GoldenParams.init(&ctx);
    defer params.deinit();
    var trainer = try es.Trainer.init(allocator, config);
    defer trainer.deinit();
    try params.register(&trainer);

    var twin_params = try GoldenParams.init(&ctx);
    defer twin_params.deinit();
    var twin = try es.Trainer.init(allocator, config);
    defer twin.deinit();
    try twin_params.register(&twin);

    // Deterministic per-member rewards; records the visit order.
    const Evaluator = struct {
        visited: std.ArrayList(usize) = .empty,
        allocator: std.mem.Allocator,

        pub fn eval(self: *@This(), member: usize) !f32 {
            try self.visited.append(self.allocator, member);
            return @as(f32, @floatFromInt(member)) * 0.5 - 0.3;
        }
    };
    var evaluator = Evaluator{ .allocator = allocator };
    defer evaluator.visited.deinit(allocator);

    _ = try trainer.step(&ctx, &evaluator);
    try std.testing.expectEqualSlices(usize, &.{ 0, 1, 2, 3 }, evaluator.visited.items);
    try std.testing.expectEqual(@as(u64, 1), trainer.iteration);

    var rewards: [4]f32 = undefined;
    for (&rewards, 0..) |*r, member| r.* = @as(f32, @floatFromInt(member)) * 0.5 - 0.3;
    _ = try twin.update(&ctx, &rewards);

    try std.testing.expectEqualSlices(f32, try twin_params.a.dataConst(), try params.a.dataConst());
    try std.testing.expectEqualSlices(f16, try twin_params.b.dataConst(), try params.b.dataConst());
    try std.testing.expectEqualSlices(u16, try twin_params.c.dataConst(), try params.c.dataConst());
    try std.testing.expectEqualSlices(f32, try twin_params.d.dataConst(), try params.d.dataConst());
}

test "es evaluateMembers: parallel replica evaluation equals sequential" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    const n = 512;
    const population = 12;
    const theta0 = try allocator.alloc(f32, n);
    defer allocator.free(theta0);
    rng.uniformFill(21, theta0, -1.0, 1.0);
    var w = try Tensor(.{.n}).fromSlice(&ctx, .{n}, theta0);
    defer w.deinit();

    var trainer = try es.Trainer.init(allocator, .{ .sigma = 0.1, .population = population, .seed = 5 });
    defer trainer.deinit();
    try trainer.addParam(&w);

    // One replica per worker; the reward is a deterministic function of the
    // materialized parameters, so parallel == sequential exactly.
    const workers = 4;
    const Evaluator = struct {
        trainer: *const es.Trainer,
        replicas: *[workers][]f32,

        pub fn evalMember(self: *const @This(), worker: usize, member: usize) !f32 {
            const replica = self.replicas[worker];
            try self.trainer.materializeMember(member, &.{std.mem.sliceAsBytes(replica)});
            var sum: f64 = 0;
            for (replica) |x| sum += x;
            return @floatCast(sum);
        }
    };
    var replicas: [workers][]f32 = undefined;
    var built: usize = 0;
    defer for (replicas[0..built]) |r| allocator.free(r);
    for (&replicas) |*r| {
        r.* = try allocator.alloc(f32, n);
        built += 1;
    }
    const evaluator = Evaluator{ .trainer = &trainer, .replicas = &replicas };

    var sequential: [population]f32 = undefined;
    try trainer.evaluateMembers(&evaluator, &sequential, 1);
    var parallel_rewards: [population]f32 = undefined;
    try trainer.evaluateMembers(&evaluator, &parallel_rewards, workers);
    try std.testing.expectEqualSlices(f32, &sequential, &parallel_rewards);

    // theta untouched by replica evaluation.
    try std.testing.expectEqualSlices(f32, theta0, try w.dataConst());
}

test "es addRegistry drives frozen and trainable entries alike" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    const Model = struct {
        w: Tensor(.{ .out, .in }),
        h: F16Tensor,
    };
    var model = Model{
        .w = try Tensor(.{ .out, .in }).variableFromSlice(&ctx, .{ 2, 3 }, &.{ 1, 2, 3, 4, 5, 6 }),
        .h = try F16Tensor.fromSlice(&ctx, .{4}, &.{ 0.5, -0.5, 1.5, -1.5 }),
    };
    defer model.h.deinit();
    defer model.w.deinit();

    var registry = ParamRegistry.init(allocator);
    defer registry.deinit();
    try registry.collect(&model);
    try std.testing.expectEqual(@as(usize, 2), registry.parameterCount());

    var trainer = try es.Trainer.init(allocator, .{ .sigma = 0.05, .population = 2, .seed = 3 });
    defer trainer.deinit();
    try std.testing.expectEqual(@as(usize, 2), try trainer.addRegistry(&registry));
    try std.testing.expectEqual(@as(usize, 2), trainer.paramCount());
    // Re-adding the same registry is a tied-weight no-op, not an error.
    try std.testing.expectEqual(@as(usize, 0), try trainer.addRegistry(&registry));
    try std.testing.expectEqual(@as(usize, 2), trainer.paramCount());
    try std.testing.expectEqual(@as(usize, 10), trainer.elementCount());

    const w_before = try allocator.dupe(f32, try model.w.dataConst());
    defer allocator.free(w_before);
    const h_before = try allocator.dupe(f16, try model.h.dataConst());
    defer allocator.free(h_before);
    try trainer.perturb(&ctx, 0);
    try std.testing.expect(!std.mem.eql(f32, w_before, try model.w.dataConst()));
    try std.testing.expect(!std.mem.eql(f16, h_before, try model.h.dataConst()));
    try trainer.restore(&ctx, 0);
}

test "es tripwires and misuse errors" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    var w = try Tensor(.{.n}).fromSlice(&ctx, .{4}, &.{ 1, 2, 3, 4 });
    defer w.deinit();
    var trainer = try es.Trainer.init(allocator, .{ .population = 2 });
    defer trainer.deinit();

    // No params yet.
    try std.testing.expectError(es.EsError.NoParams, trainer.perturb(&ctx, 0));
    try std.testing.expectError(es.EsError.NoParams, trainer.update(&ctx, &.{ 0.0, 1.0 }));

    try trainer.addParam(&w);
    try std.testing.expectError(es.EsError.DuplicateParam, trainer.addParam(&w));

    try std.testing.expectError(es.EsError.MemberNotActive, trainer.restore(&ctx, 0));
    try trainer.perturb(&ctx, 0);
    try std.testing.expectError(es.EsError.MemberActive, trainer.perturb(&ctx, 1));
    try std.testing.expectError(es.EsError.MemberActive, trainer.update(&ctx, &.{ 0.0, 1.0 }));
    try std.testing.expectError(es.EsError.MemberNotActive, trainer.restore(&ctx, 1)); // wrong member
    const dst = [_][]u8{&.{}};
    try std.testing.expectError(es.EsError.MemberActive, trainer.materializeMember(0, &dst));
    // Growing the parameter set mid-perturbation would desynchronize
    // restore (and invalidate a snapshot slab) — same tripwire.
    var w2 = try Tensor(.{.n}).fromSlice(&ctx, .{2}, &.{ 9, 9 });
    defer w2.deinit();
    try std.testing.expectError(es.EsError.MemberActive, trainer.addParam(&w2));
    try trainer.restore(&ctx, 0);
    try trainer.addParam(&w2); // fine once restored

    try std.testing.expectError(es.EsError.RewardCountMismatch, trainer.update(&ctx, &.{0.0}));
    try std.testing.expectError(es.EsError.ReplicaShapeMismatch, trainer.materializeMember(0, &dst));

    // evaluateMembers rejects workers == 0 (the `worker < workers` replica
    // bound would otherwise be violated by the implicit 0 -> 1 clamp).
    const NoopEval = struct {
        pub fn evalMember(_: *const @This(), _: usize, _: usize) !f32 {
            return 0;
        }
    };
    var zero_rewards: [2]f32 = undefined;
    try std.testing.expectError(es.EsError.InvalidConfig, trainer.evaluateMembers(&NoopEval{}, &zero_rewards, 0));
}

test "es all-equal rewards produce a bitwise no-op update" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    var w = try Tensor(.{.n}).fromSlice(&ctx, .{5}, &.{ 0.1, -0.2, 0.3, -0.4, 0.5 });
    defer w.deinit();
    var trainer = try es.Trainer.init(allocator, .{ .sigma = 0.1, .population = 3, .seed = 11 });
    defer trainer.deinit();
    try trainer.addParam(&w);

    const before = try allocator.dupe(f32, try w.dataConst());
    defer allocator.free(before);
    const stats = try trainer.update(&ctx, &.{ 0.7, 0.7, 0.7 });
    // z-scores are exactly 0 (0 / (0 + 1e-8)) => deltas are exact zeros.
    try std.testing.expectEqual(@as(f64, 0), stats.std_reward);
    try std.testing.expectEqualSlices(f32, before, try w.dataConst());
}

test "es converges on the sphere objective (reward = -||theta||^2)" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    const n = 16;
    var w = try Tensor(.{.n}).fromSlice(&ctx, .{n}, &([_]f32{1.0} ** n));
    defer w.deinit();
    var trainer = try es.Trainer.init(allocator, .{ .sigma = 0.1, .alpha = 0.05, .population = 16, .seed = 1234 });
    defer trainer.deinit();
    try trainer.addParam(&w);

    const Evaluator = struct {
        w: *const Tensor(.{.n}),

        fn sqNorm(self: *const @This()) !f64 {
            var acc: f64 = 0;
            for (try self.w.dataConst()) |x| acc += @as(f64, x) * @as(f64, x);
            return acc;
        }

        pub fn eval(self: *const @This(), member: usize) !f32 {
            _ = member; // the perturbation is already applied in place
            return @floatCast(-(try self.sqNorm()));
        }
    };
    const evaluator = Evaluator{ .w = &w };

    const initial = try evaluator.sqNorm();
    for (0..150) |_| _ = try trainer.step(&ctx, &evaluator);
    const final = try evaluator.sqNorm();
    try std.testing.expect(final < initial * 0.25);
}

// --- Ternary genome slots (BlockTQ2_0 crumbs, EGGROLL-style updates) ---

/// Test-local crumb accessors replicating the tq2_0 layout contract
/// (block e/256; r = e%256: group r/128, lane (r%128)/32, byte (r%128)%32).
fn ternaryCode(blocks: []const es.BlockTQ2_0, e: usize) u8 {
    const r = e % 256;
    const shift: u3 = @intCast(2 * ((r % 128) / 32));
    return (blocks[e / 256].qs[(r / 128) * 32 + (r % 128) % 32] >> shift) & 3;
}

fn ternarySetCode(blocks: []es.BlockTQ2_0, e: usize, code: u8) void {
    const r = e % 256;
    const shift: u3 = @intCast(2 * ((r % 128) / 32));
    const byte = &blocks[e / 256].qs[(r / 128) * 32 + (r % 128) % 32];
    byte.* = (byte.* & ~(@as(u8, 3) << shift)) | (code << shift);
}

/// Blocks with independent random crumbs in {0, 1, 2} and DISTINCT d bits
/// per block (ES must never touch d).
fn ternaryRandomBlocks(allocator: std.mem.Allocator, n_blocks: usize, seed: u64) ![]es.BlockTQ2_0 {
    const blocks = try allocator.alloc(es.BlockTQ2_0, n_blocks);
    for (blocks, 0..) |*block, b| {
        for (&block.qs, 0..) |*q, i| {
            var byte: u8 = 0;
            for (0..4) |lane| {
                const code: u8 = @intCast(rng.at(seed, @intCast((b * 64 + i) * 4 + lane)) % 3);
                byte |= code << @as(u3, @intCast(2 * lane));
            }
            q.* = byte;
        }
        block.d = @intCast(0x3C00 + b);
    }
    return blocks;
}

/// Blocks with every crumb equal to `code` (0/1/2 = w -1/0/+1).
fn ternaryConstBlocks(allocator: std.mem.Allocator, n_blocks: usize, code: u8) ![]es.BlockTQ2_0 {
    const blocks = try allocator.alloc(es.BlockTQ2_0, n_blocks);
    for (blocks) |*block| {
        @memset(&block.qs, code * 0b01010101);
        block.d = 0x3C00;
    }
    return blocks;
}

/// Replay one slot's flip stream in stream order (the perturb contract:
/// index = at(seed, 2i) % len, delta bit at(seed, 2i+1) & 1 -> +/-1, clamped
/// one-bin moves; colliding flips compose sequentially).
fn ternaryReplicaFlips(blocks: []es.BlockTQ2_0, len: usize, stream_seed: u64, flips: usize) void {
    for (0..flips) |i| {
        const index: usize = @intCast(rng.at(stream_seed, 2 * @as(u64, @intCast(i))) % @as(u64, len));
        const delta: i8 = if (rng.at(stream_seed, 2 * @as(u64, @intCast(i)) + 1) & 1 == 1) 1 else -1;
        const w = @as(i8, @intCast(ternaryCode(blocks, index))) - 1;
        ternarySetCode(blocks, index, @intCast(std.math.clamp(w + delta, -1, 1) + 1));
    }
}

const TernaryUpdateReplica = struct { expected: []es.BlockTQ2_0, touched: usize };

/// Single-voter replica of the vote-and-threshold update on one slot:
/// accumulate the votes of one coefficient-1.0 stream (the tests reward
/// member 0 with 1.0 and everyone else 0 under .none shaping, so only this
/// stream contributes nonzero votes), sort them by (|vote| desc, index asc),
/// and apply the top `cap` clamped one-bin moves to a copy of `before`.
/// Returns the copy plus the touched-nonzero count (the other binding term
/// of the applied-move budget). Caller frees `expected`.
fn ternaryReplicaUpdate(
    allocator: std.mem.Allocator,
    before: []const es.BlockTQ2_0,
    len: usize,
    stream_seed: u64,
    flips: usize,
    cap: usize,
) !TernaryUpdateReplica {
    const votes = try allocator.alloc(f32, len);
    defer allocator.free(votes);
    @memset(votes, 0);
    for (0..flips) |i| {
        const index: usize = @intCast(rng.at(stream_seed, 2 * @as(u64, @intCast(i))) % @as(u64, len));
        votes[index] += if (rng.at(stream_seed, 2 * @as(u64, @intCast(i)) + 1) & 1 == 1) 1.0 else -1.0;
    }
    const touched = try allocator.alloc(usize, len);
    defer allocator.free(touched);
    var n_touched: usize = 0;
    for (votes, 0..) |v, e| {
        if (v != 0) {
            touched[n_touched] = e;
            n_touched += 1;
        }
    }
    std.mem.sort(usize, touched[0..n_touched], @as([]const f32, votes), struct {
        fn lessThan(v: []const f32, a: usize, b: usize) bool {
            if (@abs(v[a]) != @abs(v[b])) return @abs(v[a]) > @abs(v[b]);
            return a < b;
        }
    }.lessThan);
    const expected = try allocator.dupe(es.BlockTQ2_0, before);
    for (touched[0..@min(n_touched, cap)]) |e| {
        const w = @as(i8, @intCast(ternaryCode(expected, e))) - 1;
        const sign: i8 = if (votes[e] > 0) 1 else -1;
        ternarySetCode(expected, e, @intCast(std.math.clamp(w + sign, -1, 1) + 1));
    }
    return .{ .expected = expected, .touched = n_touched };
}

test "es ternary config validation and registration errors" {
    const allocator = std.testing.allocator;
    try std.testing.expectError(es.EsError.InvalidConfig, es.Trainer.init(allocator, .{ .ternary_flip_rate = 0 }));
    try std.testing.expectError(es.EsError.InvalidConfig, es.Trainer.init(allocator, .{ .ternary_flip_rate = 1.5 }));
    try std.testing.expectError(es.EsError.InvalidConfig, es.Trainer.init(allocator, .{ .ternary_update_fraction = 0 }));
    try std.testing.expectError(es.EsError.InvalidConfig, es.Trainer.init(allocator, .{ .ternary_update_decay = -0.5 }));

    var trainer = try es.Trainer.init(allocator, .{ .population = 2 });
    defer trainer.deinit();
    const blocks = try ternaryConstBlocks(allocator, 2, 1);
    defer allocator.free(blocks);
    try std.testing.expectError(es.EsError.InvalidConfig, trainer.addTernaryParam(blocks, 0));
    try std.testing.expectError(es.EsError.InvalidConfig, trainer.addTernaryParam(blocks, 500)); // not a multiple of 256
    try std.testing.expectError(es.EsError.InvalidConfig, trainer.addTernaryParam(blocks, 256)); // blocks.len != len/256
    try trainer.addTernaryParam(blocks, 512);
    try std.testing.expectError(es.EsError.DuplicateParam, trainer.addTernaryParam(blocks, 512));
    try std.testing.expectEqual(@as(usize, 1), trainer.paramCount());
    try std.testing.expectEqual(@as(usize, 512), trainer.elementCount());
}

test "es ternary registration rejects crumb code 3, accepts the repaired genome" {
    const allocator = std.testing.allocator;
    var trainer = try es.Trainer.init(allocator, .{ .population = 2 });
    defer trainer.deinit();

    // Crumb code 3 never comes out of the encoders but can arrive in a
    // corrupt/untrusted GGUF; registration must reject it up front.
    // Registration pins len to whole blocks (len % 256 == 0), so every
    // stored crumb is logical — there is no partial-block tail to exempt.
    const blocks = try ternaryRandomBlocks(allocator, 2, 0xC0DE);
    defer allocator.free(blocks);
    ternarySetCode(blocks, 300, 3);
    try std.testing.expectError(es.EsError.InvalidConfig, trainer.addTernaryParam(blocks, 512));
    try std.testing.expectEqual(@as(usize, 0), trainer.paramCount());

    ternarySetCode(blocks, 300, 2); // repaired genome registers fine
    try trainer.addTernaryParam(blocks, 512);
    try std.testing.expectEqual(@as(usize, 1), trainer.paramCount());
}

test "es ternary perturb/restore round-trips bitwise (clamp-heavy included)" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    inline for (.{ false, true }) |clamp_heavy| {
        // Clamp-heavy: an all-(+1) genome saturates every +1 delta, so the
        // undo log must restore through no-op flips and rail collisions.
        const blocks = if (clamp_heavy)
            try ternaryConstBlocks(allocator, 3, 2)
        else
            try ternaryRandomBlocks(allocator, 3, 0xABCD);
        defer allocator.free(blocks);
        var trainer = try es.Trainer.init(allocator, .{
            .population = 4,
            .ternary_flip_rate = 0.05, // 38 flips over 768 elements: collisions occur
            .seed = 9,
        });
        defer trainer.deinit();
        try trainer.addTernaryParam(blocks, 768);
        const before = try allocator.dupe(es.BlockTQ2_0, blocks);
        defer allocator.free(before);
        for (0..4) |member| {
            try trainer.perturb(&ctx, member);
            try std.testing.expect(!std.mem.eql(u8, std.mem.sliceAsBytes(before), std.mem.sliceAsBytes(blocks)));
            try trainer.restore(&ctx, member);
            try std.testing.expectEqualSlices(u8, std.mem.sliceAsBytes(before), std.mem.sliceAsBytes(blocks));
        }
    }
}

test "es ternary perturbation is a pure function of (seed, iteration, member)" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    const blocks = try ternaryRandomBlocks(allocator, 2, 0x51ED);
    defer allocator.free(blocks);
    var trainer = try es.Trainer.init(allocator, .{ .population = 4, .ternary_flip_rate = 0.02, .seed = 123 });
    defer trainer.deinit();
    try trainer.addTernaryParam(blocks, 512);

    try trainer.perturb(&ctx, 3);
    const first = try allocator.dupe(es.BlockTQ2_0, blocks);
    defer allocator.free(first);
    try trainer.restore(&ctx, 3);
    try trainer.perturb(&ctx, 3);
    try std.testing.expectEqualSlices(u8, std.mem.sliceAsBytes(first), std.mem.sliceAsBytes(blocks));
    try trainer.restore(&ctx, 3);

    // materializeTernaryMember produces the same member bitwise, without
    // touching the shared genome.
    const replica = try allocator.alloc(es.BlockTQ2_0, 2);
    defer allocator.free(replica);
    try trainer.materializeTernaryMember(3, &.{replica});
    try std.testing.expectEqualSlices(u8, std.mem.sliceAsBytes(first), std.mem.sliceAsBytes(replica));
}

test "es ternary antithetic: odd member mirrors the even member's deltas" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    // Zero genome (every w = 0, code 1) exposes the raw deltas; the clamp
    // is odd-symmetric on [-1, +1], so colliding flips mirror too.
    const len = 512;
    const base = try ternaryConstBlocks(allocator, 2, 1);
    defer allocator.free(base);
    var trainer = try es.Trainer.init(allocator, .{
        .population = 4,
        .antithetic = true,
        .ternary_flip_rate = 16.0 / 512.0,
        .seed = 33,
    });
    defer trainer.deinit();
    try trainer.addTernaryParam(base, len);

    const even = try allocator.alloc(es.BlockTQ2_0, 2);
    defer allocator.free(even);
    const odd = try allocator.alloc(es.BlockTQ2_0, 2);
    defer allocator.free(odd);
    try trainer.materializeTernaryMember(2, &.{even});
    try trainer.materializeTernaryMember(3, &.{odd});

    var flipped: usize = 0;
    for (0..len) |e| {
        const w_even = @as(i8, @intCast(ternaryCode(even, e))) - 1;
        const w_odd = @as(i8, @intCast(ternaryCode(odd, e))) - 1;
        try std.testing.expectEqual(w_even, -w_odd);
        if (w_even != 0) flipped += 1;
        try std.testing.expectEqual(@as(u8, 1), ternaryCode(base, e)); // shared genome untouched
    }
    try std.testing.expect(flipped > 0);
}

test "es ternary update: top-K one-bin moves toward sign(vote), crumbs ternary, d untouched" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    const len = 512;
    const cap = 8; // round(len * ternary_update_fraction)
    const blocks = try ternaryRandomBlocks(allocator, len / 256, 0x7E57);
    defer allocator.free(blocks);
    const before = try allocator.dupe(es.BlockTQ2_0, blocks);
    defer allocator.free(before);

    var trainer = try es.Trainer.init(allocator, .{
        .population = 2,
        .reward_norm = .none, // coefficients == rewards: exact replication below
        .ternary_flip_rate = 32.0 / 512.0,
        .ternary_update_fraction = 8.0 / 512.0,
        .seed = 21,
    });
    defer trainer.deinit();
    try trainer.addTernaryParam(blocks, len);

    // Replicate the vote table from the PUBLIC seed derivations before the
    // update advances the iteration: member 0 votes with coefficient 1;
    // member 1's zero-coefficient flips add exact zeros (dropped by the
    // nonzero filter), so only member 0's stream matters.
    const stream_seed = es.Trainer.ternarySlotStreamSeed(trainer.ternaryMemberSeed(0), 0);
    const flips = trainer.ternaryFlipCount(len);
    try std.testing.expectEqual(@as(usize, 32), flips);
    var votes = [_]f32{0} ** len;
    for (0..flips) |i| {
        const index: usize = @intCast(rng.at(stream_seed, 2 * @as(u64, @intCast(i))) % @as(u64, len));
        const delta: f32 = if (rng.at(stream_seed, 2 * @as(u64, @intCast(i)) + 1) & 1 == 1) 1.0 else -1.0;
        votes[index] += delta;
    }

    _ = try trainer.update(&ctx, &.{ 1.0, 0.0 });

    // Expected genome: sort nonzero votes by (|vote| desc, index asc), move
    // the top `cap` one bin toward sign(vote) with ternary clamping.
    var touched: [len]usize = undefined;
    var n_touched: usize = 0;
    for (votes, 0..) |v, e| {
        if (v != 0) {
            touched[n_touched] = e;
            n_touched += 1;
        }
    }
    std.mem.sort(usize, touched[0..n_touched], @as([]const f32, &votes), struct {
        fn lessThan(v: []const f32, a: usize, b: usize) bool {
            if (@abs(v[a]) != @abs(v[b])) return @abs(v[a]) > @abs(v[b]);
            return a < b;
        }
    }.lessThan);
    const expected = try allocator.dupe(es.BlockTQ2_0, before);
    defer allocator.free(expected);
    for (touched[0..@min(n_touched, cap)]) |e| {
        const w = @as(i8, @intCast(ternaryCode(expected, e))) - 1;
        const sign: i8 = if (votes[e] > 0) 1 else -1;
        ternarySetCode(expected, e, @intCast(std.math.clamp(w + sign, -1, 1) + 1));
    }
    try std.testing.expectEqualSlices(u8, std.mem.sliceAsBytes(expected), std.mem.sliceAsBytes(blocks));

    // The named invariants, asserted directly as well.
    var changed: usize = 0;
    for (0..len) |e| {
        const now = ternaryCode(blocks, e);
        try std.testing.expect(now <= 2);
        const was = ternaryCode(before, e);
        if (now != was) {
            changed += 1;
            const diff = @as(i8, @intCast(now)) - @as(i8, @intCast(was));
            try std.testing.expect(diff == 1 or diff == -1); // exactly one bin
            try std.testing.expectEqual(votes[e] > 0, diff == 1); // toward sign(vote)
        }
    }
    try std.testing.expect(changed > 0);
    try std.testing.expect(changed <= cap);
    for (before, blocks) |b, a| try std.testing.expectEqual(b.d, a.d);
}

test "es ternary update decay shrinks the top-K budget at iteration 1" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    const len = 512;
    // fraction 16/512 -> undecayed cap 16; decay 1 at iteration 1 halves it
    // to round(16 / (1 + 1*1)) = 8. A broken schedule fails the exact count
    // below: no decay applies 16 moves, an off-by-one iteration rounds
    // 16/3 to 5.
    const cap_iter1 = 8;
    // All-zero genome: no move can clamp into a no-op, so the changed-crumb
    // count equals the applied-move count.
    const blocks = try ternaryConstBlocks(allocator, len / 256, 1);
    defer allocator.free(blocks);

    var trainer = try es.Trainer.init(allocator, .{
        .population = 2,
        .reward_norm = .none, // coefficients == rewards: exact replication below
        .ternary_flip_rate = 32.0 / 512.0,
        .ternary_update_fraction = 16.0 / 512.0,
        .ternary_update_decay = 1.0,
        .seed = 63,
    });
    defer trainer.deinit();
    try trainer.addTernaryParam(blocks, len);

    // First update: zero coefficients vote nothing, so the genome stays
    // all-zero while the iteration (the decay schedule input) advances.
    _ = try trainer.update(&ctx, &.{ 0.0, 0.0 });
    try std.testing.expectEqual(@as(u64, 1), trainer.iteration);
    for (0..len) |e| try std.testing.expectEqual(@as(u8, 1), ternaryCode(blocks, e));

    // Replicate member 0's iteration-1 vote table from the public seed API
    // (member 1's coefficient is 0: exact-zero votes are dropped).
    const stream_seed = es.Trainer.ternarySlotStreamSeed(trainer.ternaryMemberSeed(0), 0);
    const replica = try ternaryReplicaUpdate(allocator, blocks, len, stream_seed, trainer.ternaryFlipCount(len), cap_iter1);
    defer allocator.free(replica.expected);
    try std.testing.expect(replica.touched > cap_iter1); // the budget, not the vote count, binds

    _ = try trainer.update(&ctx, &.{ 1.0, 0.0 });
    try std.testing.expectEqualSlices(u8, std.mem.sliceAsBytes(replica.expected), std.mem.sliceAsBytes(blocks));
    var changed: usize = 0;
    for (0..len) |e| changed += @intFromBool(ternaryCode(blocks, e) != 1);
    try std.testing.expectEqual(@min(replica.touched, cap_iter1), changed);
}

test "es ternary multi-slot: flip streams, perturbations, and votes stay per-slot" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    const len_a = 256;
    const len_b = 512;
    const blocks_a = try ternaryRandomBlocks(allocator, len_a / 256, 0xA5A5);
    defer allocator.free(blocks_a);
    const blocks_b = try ternaryRandomBlocks(allocator, len_b / 256, 0x5A5A);
    defer allocator.free(blocks_b);

    var trainer = try es.Trainer.init(allocator, .{
        .population = 2,
        .reward_norm = .none, // coefficients == rewards: exact replication below
        .ternary_flip_rate = 16.0 / 512.0, // 8 flips on slot 0, 16 on slot 1
        .ternary_update_fraction = 8.0 / 512.0, // top-K caps 4 and 8
        .seed = 47,
    });
    defer trainer.deinit();
    try trainer.addTernaryParamNamed(blocks_a, len_a, "a");
    try trainer.addTernaryParamNamed(blocks_b, len_b, "b");
    try std.testing.expectEqual(@as(usize, 2), trainer.paramCount());
    try std.testing.expectEqual(@as(usize, len_a + len_b), trainer.elementCount());

    // The two slots draw DISTINCT flip streams for the same member; compare
    // the raw draws under a common modulus so the length difference cannot
    // mask identical streams.
    const member_seed = trainer.ternaryMemberSeed(0);
    const seed_a = es.Trainer.ternarySlotStreamSeed(member_seed, 0);
    const seed_b = es.Trainer.ternarySlotStreamSeed(member_seed, 1);
    var streams_differ = false;
    for (0..2 * trainer.ternaryFlipCount(len_a)) |j| {
        if (rng.at(seed_a, @intCast(j)) % len_a != rng.at(seed_b, @intCast(j)) % len_a) streams_differ = true;
    }
    try std.testing.expect(streams_differ);

    // In-place perturb applies each slot's OWN stream (replicated bitwise
    // from the public seed API); restore unwinds both undo logs.
    const before_a = try allocator.dupe(es.BlockTQ2_0, blocks_a);
    defer allocator.free(before_a);
    const before_b = try allocator.dupe(es.BlockTQ2_0, blocks_b);
    defer allocator.free(before_b);
    const perturbed_a = try allocator.dupe(es.BlockTQ2_0, blocks_a);
    defer allocator.free(perturbed_a);
    ternaryReplicaFlips(perturbed_a, len_a, seed_a, trainer.ternaryFlipCount(len_a));
    const perturbed_b = try allocator.dupe(es.BlockTQ2_0, blocks_b);
    defer allocator.free(perturbed_b);
    ternaryReplicaFlips(perturbed_b, len_b, seed_b, trainer.ternaryFlipCount(len_b));
    try trainer.perturb(&ctx, 0);
    try std.testing.expectEqualSlices(u8, std.mem.sliceAsBytes(perturbed_a), std.mem.sliceAsBytes(blocks_a));
    try std.testing.expectEqualSlices(u8, std.mem.sliceAsBytes(perturbed_b), std.mem.sliceAsBytes(blocks_b));
    try trainer.restore(&ctx, 0);
    try std.testing.expectEqualSlices(u8, std.mem.sliceAsBytes(before_a), std.mem.sliceAsBytes(blocks_a));
    try std.testing.expectEqualSlices(u8, std.mem.sliceAsBytes(before_b), std.mem.sliceAsBytes(blocks_b));

    // The update votes per slot: each genome must land exactly on its OWN
    // replicated top-K table (cross-slot vote leakage — e.g. a missing
    // per-slot vote reset — would push slot 0's indices into slot 1's cap).
    const replica_a = try ternaryReplicaUpdate(allocator, before_a, len_a, seed_a, trainer.ternaryFlipCount(len_a), 4);
    defer allocator.free(replica_a.expected);
    const replica_b = try ternaryReplicaUpdate(allocator, before_b, len_b, seed_b, trainer.ternaryFlipCount(len_b), 8);
    defer allocator.free(replica_b.expected);
    try std.testing.expect(replica_a.touched > 0);
    try std.testing.expect(replica_b.touched > 0);
    _ = try trainer.update(&ctx, &.{ 1.0, 0.0 });
    try std.testing.expectEqualSlices(u8, std.mem.sliceAsBytes(replica_a.expected), std.mem.sliceAsBytes(blocks_a));
    try std.testing.expectEqualSlices(u8, std.mem.sliceAsBytes(replica_b.expected), std.mem.sliceAsBytes(blocks_b));
}

test "es ternary: mixed float+ternary trainer leaves float slots bitwise unchanged" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    const n = 512;
    const theta0 = try allocator.alloc(f32, n);
    defer allocator.free(theta0);
    rng.uniformFill(17, theta0, -1.0, 1.0);
    const config = es.Config{ .sigma = 0.05, .alpha = 0.02, .population = 4, .seed = 42 };
    const rewards = [_]f32{ 0.3, -1.2, 0.75, 0.0 };

    // Float-only twin.
    var w_float = try Tensor(.{.n}).fromSlice(&ctx, .{n}, theta0);
    defer w_float.deinit();
    var float_only = try es.Trainer.init(allocator, config);
    defer float_only.deinit();
    try float_only.addParam(&w_float);

    // Mixed twin: the ternary slot registers FIRST — float noise streams
    // key on the float slot index, so they must not shift.
    const blocks = try ternaryRandomBlocks(allocator, 2, 0xB17);
    defer allocator.free(blocks);
    var w_mixed = try Tensor(.{.n}).fromSlice(&ctx, .{n}, theta0);
    defer w_mixed.deinit();
    var mixed = try es.Trainer.init(allocator, config);
    defer mixed.deinit();
    try mixed.addTernaryParamNamed(blocks, 512, "genome");
    try mixed.addParam(&w_mixed);
    try std.testing.expectEqual(@as(usize, 2), mixed.paramCount());
    try std.testing.expectEqual(@as(usize, n + 512), mixed.elementCount());

    // Perturbation of the float slot is bitwise identical...
    try float_only.perturb(&ctx, 1);
    try mixed.perturb(&ctx, 1);
    try std.testing.expectEqualSlices(f32, try w_float.dataConst(), try w_mixed.dataConst());
    try float_only.restore(&ctx, 1);
    try mixed.restore(&ctx, 1);

    // ...and so is the update on the same rewards.
    _ = try float_only.update(&ctx, &rewards);
    _ = try mixed.update(&ctx, &rewards);
    try std.testing.expectEqualSlices(f32, try w_float.dataConst(), try w_mixed.dataConst());
}

test "es ternary converges toward a target genome (hamming reward)" {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer std.testing.expect(gpa.deinit() == .ok) catch @panic("leak");
    const allocator = gpa.allocator();
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    const len = 512;
    const blocks = try ternaryConstBlocks(allocator, 2, 1); // start at all-zero weights
    defer allocator.free(blocks);
    var target: [len]u8 = undefined;
    for (&target, 0..) |*t, e| t.* = @intCast(rng.at(99, @intCast(e)) % 3);

    var trainer = try es.Trainer.init(allocator, .{
        .population = 32,
        .antithetic = true,
        .ternary_flip_rate = 4.0 / 512.0,
        .ternary_update_fraction = 8.0 / 512.0,
        .seed = 7,
    });
    defer trainer.deinit();
    try trainer.addTernaryParam(blocks, len);

    const Evaluator = struct {
        blocks: []const es.BlockTQ2_0,
        target: []const u8,

        fn distance(self: *const @This()) usize {
            var dist: usize = 0;
            for (self.target, 0..) |t, e| {
                if (ternaryCode(self.blocks, e) != t) dist += 1;
            }
            return dist;
        }

        pub fn eval(self: *const @This(), member: usize) !f32 {
            _ = member; // the flips are already applied in place
            return -@as(f32, @floatFromInt(self.distance())) / @as(f32, @floatFromInt(self.target.len));
        }
    };
    const evaluator = Evaluator{ .blocks = blocks, .target = &target };

    const initial = evaluator.distance();
    for (0..300) |_| _ = try trainer.step(&ctx, &evaluator);
    const final = evaluator.distance();
    try std.testing.expect(final * 5 <= initial * 2); // >= 60% closer
}

test "es ternary-only trainer: captureAnchor succeeds, anchored decay is a float no-op" {
    const allocator = std.testing.allocator;
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    // Both slot kinds empty still rejects captureAnchor.
    var empty = try es.Trainer.init(allocator, .{ .population = 2, .anchor_decay = .l2, .anchor_lambda = 10 });
    defer empty.deinit();
    try std.testing.expectError(es.EsError.NoParams, empty.captureAnchor());

    // Ternary-only trainer: AWD is a float-slot regularizer, so the anchor
    // is an empty slab and update must not fail AnchorMissing.
    const len = 512;
    const blocks = try ternaryRandomBlocks(allocator, len / 256, 0xA7C4);
    defer allocator.free(blocks);
    var trainer = try es.Trainer.init(allocator, .{
        .population = 2,
        .anchor_decay = .l2,
        .anchor_lambda = 10, // alpha*lambda = 0.005 < 1
        .ternary_flip_rate = 8.0 / 512.0,
        .ternary_update_fraction = 8.0 / 512.0,
        .seed = 11,
    });
    defer trainer.deinit();
    try trainer.addTernaryParam(blocks, len);
    try trainer.captureAnchor();

    // A full perturb/evaluate/restore/update cycle completes (this errored
    // AnchorMissing forever before captureAnchor accepted ternary-only)...
    const Evaluator = struct {
        pub fn eval(_: *const @This(), member: usize) !f32 {
            return @floatFromInt(member % 2);
        }
    };
    _ = try trainer.step(&ctx, &Evaluator{});
    try std.testing.expectEqual(@as(u64, 1), trainer.iteration);
    // ...and the genome stays a valid ternary model.
    for (0..len) |e| try std.testing.expect(ternaryCode(blocks, e) <= 2);
}

test "es update: allocation failure leaves theta, genome, and iteration untouched" {
    const allocator = std.testing.allocator;
    var ctx: ExecContext = undefined;
    ctx.init(allocator);
    defer ctx.deinit();

    const n = 32;
    const len = 256;
    var theta0: [n]f32 = undefined;
    rng.uniformFill(3, &theta0, -1.0, 1.0);
    const config = es.Config{ .population = 2, .reward_norm = .none, .seed = 5 };
    const rewards = [_]f32{ 1.0, 0.0 };
    const blocks0 = try ternaryRandomBlocks(allocator, len / 256, 0xFA11);
    defer allocator.free(blocks0);

    // Reference outcome from an unconstrained twin.
    var expected_theta: [n]f32 = undefined;
    const expected_blocks = try allocator.dupe(es.BlockTQ2_0, blocks0);
    defer allocator.free(expected_blocks);
    {
        var w = try Tensor(.{.n}).fromSlice(&ctx, .{n}, &theta0);
        defer w.deinit();
        var twin = try es.Trainer.init(allocator, config);
        defer twin.deinit();
        try twin.addParam(&w);
        try twin.addTernaryParam(expected_blocks, len);
        _ = try twin.update(&ctx, &rewards);
        @memcpy(&expected_theta, try w.dataConst());
    }

    // Sweep the failure point across every trainer-side allocation: a
    // failed update must be a no-op on theta, the genome, and `iteration`
    // (the mutate-last contract — the ternary vote scratch in particular
    // must allocate BEFORE the float slots change); past the last
    // allocation the update must succeed with the reference outcome.
    var failed_once = false;
    var fail_index: usize = 0;
    while (fail_index < 1000) : (fail_index += 1) {
        var failing = std.testing.FailingAllocator.init(allocator, .{ .fail_index = fail_index });
        var w = try Tensor(.{.n}).fromSlice(&ctx, .{n}, &theta0);
        defer w.deinit();
        const blocks = try allocator.dupe(es.BlockTQ2_0, blocks0);
        defer allocator.free(blocks);
        var trainer = try es.Trainer.init(failing.allocator(), config);
        defer trainer.deinit();
        // Registration allocates too; a failure there just advances the sweep.
        trainer.addParam(&w) catch |err| switch (err) {
            error.OutOfMemory => continue,
            else => return err,
        };
        trainer.addTernaryParam(blocks, len) catch |err| switch (err) {
            error.OutOfMemory => continue,
            else => return err,
        };
        if (trainer.update(&ctx, &rewards)) |_| {
            try std.testing.expectEqualSlices(f32, &expected_theta, try w.dataConst());
            try std.testing.expectEqualSlices(u8, std.mem.sliceAsBytes(expected_blocks), std.mem.sliceAsBytes(blocks));
            try std.testing.expectEqual(@as(u64, 1), trainer.iteration);
            try std.testing.expect(failed_once); // the sweep saw real OOM failures first
            return;
        } else |err| {
            if (err != error.OutOfMemory) return err;
            failed_once = true;
            try std.testing.expectEqualSlices(f32, &theta0, try w.dataConst());
            try std.testing.expectEqualSlices(u8, std.mem.sliceAsBytes(blocks0), std.mem.sliceAsBytes(blocks));
            try std.testing.expectEqual(@as(u64, 0), trainer.iteration);
        }
    }
    return error.TestUnexpectedResult; // the sweep never reached a successful update
}
